import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildXpraProbeCommand, buildXpraStartCommand, displayForPort, getAllowedLinuxPocApps, normalizePocApp, resolvePocApp, setXpraPocAppResolver } from '../src/linuxRuntime/xpraPoc.js';
import { scopedOwnerId } from '../src/linuxRuntime/routes.js';
import { __test as proxyTest } from '../src/linuxRuntime/xpraProxy.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, '../..');

test('POC1 resolves only exact scanner-backed IDs and never treats a client value as a binary', async () => {
  const appId = 'linux-0123456789abcdef0123456789abcdef';
  const discovered = [{ id: appId, name: 'L3afpad', launchArgv: ['/usr/bin/l3afpad', '--new-window'], categories: ['Utility'] }];
  setXpraPocAppResolver({
    async list() { return discovered; },
    async resolve(appId) { return discovered.find(app => app.id === appId) || null; }
  });
  try {
    const apps = await getAllowedLinuxPocApps('kali-linux');
    assert.deepEqual(apps.map(app => app.id), [appId]);
    assert.equal('argv' in apps[0], false);
    assert.equal('command' in apps[0], false);
    const resolved = await resolvePocApp(appId, 'kali-linux');
    assert.equal(resolved?.title, 'L3afpad');
    assert.deepEqual(resolved?.argv, ['/usr/bin/l3afpad', '--new-window']);
    assert.equal(await resolvePocApp('l3afpad', 'kali-linux'), null);
    assert.equal(normalizePocApp('invalid-app-xyz; rm -rf /'), null);
    assert.equal(normalizePocApp('sh -c calc.exe'), null);
  } finally {
    setXpraPocAppResolver();
  }
});
test('Firefox containment policy is executable-derived and creates a per-session profile', () => { const source = fs.readFileSync(path.join(repoRoot, 'backend', 'src', 'linuxRuntime', 'xpraPoc.js'), 'utf8'); assert.match(source, /binary === 'firefox' \|\| binary === 'firefox-esr'/); assert.match(source, /argv\.includes\('--no-remote'\)/); assert.match(source, /`\/tmp\/cloudos-firefox-poc-\$\{sessionId\}`/); assert.doesNotMatch(source, /const\s+ALLOWED_APPS/); });
test('B-01: Xpra loopback socket requires a per-session capability password', () => { const command = buildXpraStartCommand({ appCommand: 'xclock', port: 14500, sessionId: 'test-session', password: '0123456789abcdef0123456789abcdef' }); assert.match(command, /export XPRA_PASSWORD=/); assert.match(command, /--bind-tcp=0\.0\.0\.0:14500,auth=env/); assert.doesNotMatch(command, /auth=allow/); assert.match(command, /--start-new-commands=no/); assert.equal(displayForPort(14549), 149); });
test('B-01a: Xpra child is forced onto X11 and cannot inherit the host Wayland route', () => { const command = buildXpraStartCommand({ appArgv: ['firefox-esr', '--no-remote', '--profile', '/tmp/cloudos-firefox-poc-contained-firefox'], port: 14500, sessionId: 'contained-firefox', password: '0123456789abcdef0123456789abcdef' }); assert.match(command, /unset DISPLAY WAYLAND_DISPLAY WAYLAND_SOCKET PULSE_SERVER/); assert.match(command, /export GDK_BACKEND=x11/); assert.match(command, /MOZ_ENABLE_WAYLAND=0/); assert.match(command, /QT_QPA_PLATFORM=xcb/); assert.match(command, /ELECTRON_OZONE_PLATFORM_HINT=x11/); assert.match(command, /install -d [^;]*cloudos-firefox-poc-contained-firefox/); assert.match(command, /--start-child=/); assert.match(command, /firefox-esr/); assert.match(command, /cloudos-firefox-poc-contained-firefox/); });
test('B-01aa: runtime PID inspection correlates global process tree without exposing the private Xpra socket', () => { const source = fs.readFileSync(path.join(repoRoot, 'backend', 'src', 'linuxRuntime', 'xpraPoc.js'), 'utf8'); assert.match(source, /execWslSystem\(\['ps', '-eo'/); assert.match(source, /--session-name=cloudos-poc1-\$\{sessionId\}/); assert.match(source, /processDescendsFrom/); assert.match(source, /inspectSessionPids/); assert.doesNotMatch(source, /const runtimeDirectory = `\/run\/xpra/); });
test('B-01b: desktop launch has one contained Xpra implementation and no warm-pool resolver', () => { const routes = fs.readFileSync(path.join(repoRoot, 'backend', 'src', 'linuxRuntime', 'routes.js'), 'utf8'); const proxy = fs.readFileSync(path.join(repoRoot, 'backend', 'src', 'linuxRuntime', 'xpraProxy.js'), 'utf8'); const desktopWindow = fs.readFileSync(path.join(repoRoot, 'frontend', 'src', 'apps', 'LinuxAppWindow', 'LinuxAppWindow.tsx'), 'utf8'); const pocWindow = fs.readFileSync(path.join(repoRoot, 'frontend', 'src', 'apps', 'LinuxRuntimePoc', 'LinuxRuntimePoc.tsx'), 'utf8'); assert.match(routes, /startXpraPoc\(\{[\s\S]*app:\s*req\.body\?\.appId/); assert.doesNotMatch(routes, /launchFastLinuxApp|warmPoolManager/); assert.doesNotMatch(proxy, /resolveWarmSession|warmPoolManager/); assert.match(desktopWindow, /src=\{resolveApiUrl\(session\.clientUrl\)\}/); assert.match(desktopWindow, /timeoutMs: 45_000/); assert.match(desktopWindow, /event\.source !== iframe\.contentWindow/); assert.match(desktopWindow, /event\.data\?\.sessionId !== session\.id/); assert.doesNotMatch(desktopWindow, /onLoad=\{handleFrameLoad\}/); assert.match(pocWindow, /resolveApiUrl\(activeSession\.clientUrl\)/); });
test('B-01c: native catalog fails closed instead of launching WSLg desktop windows', () => { const source = fs.readFileSync(path.join(repoRoot, 'backend', 'src', 'apps', 'appCatalog.js'), 'utf8'); assert.match(source, /app\.source === 'linux'[\s\S]*app\.kind === 'linux-desktop'[\s\S]*LINUX_CONTAINMENT_REQUIRED/); assert.doesNotMatch(source, /exec gtk-launch/); assert.doesNotMatch(source, /exec gio launch/); });
test('B-01d: Xpra proxy reports a correlated painted canvas instead of treating iframe load as render', () => { const proxy = fs.readFileSync(path.join(repoRoot, 'backend', 'src', 'linuxRuntime', 'xpraProxy.js'), 'utf8'); assert.match(proxy, /source: 'xpra-canvas'/); assert.match(proxy, /canvasWidth: canvas\.width/); assert.match(proxy, /requestAnimationFrame\(function\(\) \{/); });
test('B-01da: contained Xpra client keeps keyboard input enabled', () => { const source = fs.readFileSync(path.join(repoRoot, 'backend', 'src', 'linuxRuntime', 'xpraPoc.js'), 'utf8'); const clientUrlLine = source.split(/\r?\n/).find(line => line.includes("clientUrl: ['ready', 'degraded']")); assert.ok(clientUrlLine); assert.doesNotMatch(clientUrlLine, /keyboard=no/); assert.match(clientUrlLine, /clipboard=no/); });
test('B-01db: contained Xpra surface performs a correlated focus handoff', () => { const desktopWindow = fs.readFileSync(path.join(repoRoot, 'frontend', 'src', 'apps', 'LinuxAppWindow', 'LinuxAppWindow.tsx'), 'utf8'); const shim = proxyTest.createOpaqueShim('focus-session', 'secret'); assert.match(shim, /addEventListener\('pointerdown',[\s\S]*window\.focus\(\)[\s\S]*type: 'xpra-focus-request'[\s\S]*sessionId: "focus-session"[\s\S]*}, true\)/); assert.ok(shim.indexOf('window.focus()') < shim.indexOf("type: 'xpra-focus-request'")); assert.match(desktopWindow, /event\.source !== iframe\.contentWindow/); assert.match(desktopWindow, /event\.origin !== expectedOrigin/); assert.match(desktopWindow, /event\.data\?\.sessionId !== session\.id/); assert.match(desktopWindow, /event\.data\?\.type === 'xpra-focus-request'/); assert.match(desktopWindow, /iframe\?\.focus\(\{ preventScroll: true \}\)/); assert.match(desktopWindow, /iframe\?\.contentWindow\?\.focus\(\)/); assert.match(desktopWindow, /tabIndex=\{0\}/); assert.match(desktopWindow, /onLoad=\{focusContainedSurface\}/); assert.match(desktopWindow, /sandbox="allow-scripts allow-forms allow-pointer-lock allow-same-origin"/); assert.match(desktopWindow, /win\?\.isActive/); });
test('B-01e: terminal WSL enters fail-closed containment before exposing a shell', () => { const terminal = fs.readFileSync(path.join(repoRoot, 'backend', 'src', 'terminal', 'websocket.js'), 'utf8'); const containment = fs.readFileSync(path.join(repoRoot, 'backend', 'src', 'terminal', 'wslTerminalContainment.js'), 'utf8'); assert.match(terminal, /buildContainedLegacyShellArgs\(targetDistro\)/); assert.match(containment, /--mount/); assert.match(containment, /--pid/); assert.match(containment, /mount -t tmpfs[^\n]* \/run/); assert.match(containment, /mount -t tmpfs[^\n]* \/tmp/); assert.match(containment, /\/mnt\/wslg/); assert.match(containment, /\/run\/WSL/); assert.match(containment, /mount --bind "\$mask_file" \/init/); assert.match(containment, /--reuid="\$target_uid"/); assert.match(containment, /--seccomp-filter/); assert.match(containment, /\/mnt\/c\/Windows\/System32\/cmd\.exe \/c exit/); assert.match(containment, /CLOUDOS_TERMINAL_CONTAINMENT_CANARY_FAILED/); assert.match(containment, /env -i/); });
test('B-02: owner namespace changes with authenticated principal', () => { const a = scopedOwnerId('user-a', 'window-1'); const b = scopedOwnerId('user-b', 'window-1'); assert.notEqual(a, b); assert.match(a, /^[a-f0-9]{24}:window-1$/); assert.equal(scopedOwnerId('user-a', 'window-1'), a); });
test('B-03: proxy permits the CloudOS embedding context and strips cookies', () => { const csp = proxyTest.rewriteCsp("default-src 'self'; frame-ancestors 'none'; sandbox allow-same-origin allow-scripts"); assert.doesNotMatch(csp, /(?:^|;)\s*sandbox\b/); assert.match(csp, /frame-ancestors \*/); const headers = proxyTest.buildResponseHeaders({ 'set-cookie': 'secret=x', 'content-type': 'text/html' }, { id: 'x', proxyToken: 't', port: 14500 }); assert.equal(headers['set-cookie'], undefined); assert.equal(headers['Referrer-Policy'], 'no-referrer'); });
test('B-04: runtime source fails closed when WSLInterop remains enabled', () => { const source = fs.readFileSync(path.join(repoRoot, 'backend', 'src', 'linuxRuntime', 'xpraPoc.js'), 'utf8'); assert.match(source, /\/proc\/sys\/fs\/binfmt_misc\/WSLInterop/); assert.match(source, /WSL_INTEROP_ENABLED/); assert.match(source, /if \(!interop\.ok\) return \{ ready: false/); });
test('POC1 preflight requires Xpra and selected app instead of installing them', () => { const probe = buildXpraProbeCommand('xeyes'); assert.match(probe, /command -v xpra/); assert.match(probe, /APP_MISSING:xeyes/); assert.doesNotMatch(probe, /apt|dnf|pacman|zypper|snap|flatpak/); });
test('POC1 rejects ports outside its loopback range', () => { assert.throws(() => buildXpraStartCommand({ appCommand: 'xclock', port: 80, password: '0123456789abcdef' }), /fora da faixa/); assert.throws(() => buildXpraStartCommand({ appCommand: 'xclock', port: 16000, password: '0123456789abcdef' }), /fora da faixa/); });
test('POC1 CloudOS proxy strips capability prefix before forwarding to Xpra', () => { assert.deepEqual(proxyTest.parseProxyRequest('/__cloudos/linux-runtime/poc1/xpra-1/secret/js/Client.js?x=1'), { id: 'xpra-1', token: 'secret', targetPath: '/js/Client.js?x=1' }); });
test('POC1 dev server still forwards capability HTTP and WebSocket traffic to backend', () => { const viteConfig = fs.readFileSync(path.join(repoRoot, 'frontend', 'vite.config.ts'), 'utf8'); assert.match(viteConfig, /['"]\/__cloudos['"]\s*:\s*\{[^}]*target:\s*backendHttpTarget[^}]*ws:\s*true/s); });
test('CloudOS minimize preserves mounted app lifecycle', () => { const source = fs.readFileSync(path.join(repoRoot, 'frontend', 'src', 'components', 'Window', 'Window.tsx'), 'utf8'); assert.doesNotMatch(source, /if\s*\(\s*!win\s*\|\|\s*win\.isMinimized\s*\)\s*return\s+null/); assert.match(source, /display:\s*win\.isMinimized\s*\?\s*['"]none['"]\s*:\s*undefined/); });
test('POC1 proxy rewrites Xpra redirects back into capability path', () => { const session = { id: 'xpra-1', proxyToken: 'abc', port: 14500 }; assert.equal(proxyTest.rewriteLocation('/connect.html', session), '/__cloudos/linux-runtime/poc1/xpra-1/abc/connect.html'); });
