export const appExes: [string, string, string, string, string, string, string][] = [
  ['C:\\Program Files\\ObsidianOS Apps\\notepad.obx', 'notepad.obx', 'C:\\Program Files\\ObsidianOS Apps', 'notepad', '📝', 'productivity', 'Bloco de Notas'],
  ['C:\\Program Files\\ObsidianOS Apps\\calc.obx', 'calc.obx', 'C:\\Program Files\\ObsidianOS Apps', 'calculator', '🧮', 'utilities', 'Calculadora'],
  ['C:\\Program Files\\ObsidianOS Apps\\cmd.obx', 'cmd.obx', 'C:\\Program Files\\ObsidianOS Apps', 'terminal', '💻', 'system', 'Terminal Offline'],
  ['C:\\Program Files\\ObsidianOS Apps\\cloudos-terminal.obx', 'cloudos-terminal.obx', 'C:\\Program Files\\ObsidianOS Apps', 'cloudos-terminal', '⚡', 'system', 'CloudOS Terminal'],
  ['C:\\Program Files\\ObsidianOS Apps\\cloudos-files.obx', 'cloudos-files.obx', 'C:\\Program Files\\ObsidianOS Apps', 'cloudos-files', '☁️', 'system', 'CloudOS Files'],
  ['C:\\Program Files\\ObsidianOS Apps\\workflow-workspace.obx', 'workflow-workspace.obx', 'C:\\Program Files\\ObsidianOS Apps', 'workflow-workspace', '🗂️', 'productivity', 'Workspace'],
  ['C:\\Program Files\\ObsidianOS Apps\\sysmon.obx', 'sysmon.obx', 'C:\\Program Files\\ObsidianOS Apps', 'system-monitor', '📈', 'system', 'System Monitor'],
  ['C:\\Program Files\\ObsidianOS Apps\\install-linux.obx', 'install-linux.obx', 'C:\\Program Files\\ObsidianOS Apps', 'install-linux', '◈', 'system', 'Central Windows + Linux'],
  ['C:\\Program Files\\ObsidianOS Apps\\linux-runtime-poc.obx', 'linux-runtime-poc.obx', 'C:\\Program Files\\ObsidianOS Apps', 'linux-runtime-poc', '🐧', 'system', 'Linux Runtime POC 1'],
  ['C:\\Program Files\\ObsidianOS Apps\\env-doctor.obx', 'env-doctor.obx', 'C:\\Program Files\\ObsidianOS Apps', 'env-doctor', '🩺', 'system', 'Environment Doctor'],
  ['C:\\Program Files\\ObsidianOS Apps\\explorer.obx', 'explorer.obx', 'C:\\Program Files\\ObsidianOS Apps', 'file-explorer', '📁', 'system', 'Explorador de Arquivos'],
  ['C:\\Program Files\\ObsidianOS Apps\\control.obx', 'control.obx', 'C:\\Program Files\\ObsidianOS Apps', 'settings', '⚙️', 'system', 'Configurações'],
  ['C:\\Program Files\\ObsidianOS Apps\\taskmgr.obx', 'taskmgr.obx', 'C:\\Program Files\\ObsidianOS Apps', 'task-manager', '📊', 'system', 'Gerenciador de Tarefas'],
  ['C:\\Program Files\\ObsidianOS Apps\\msedge.obx', 'msedge.obx', 'C:\\Program Files\\ObsidianOS Apps', 'browser', '🌐', 'productivity', 'Navegador Web'],
  ['C:\\Program Files\\ObsidianOS Apps\\windows-installer.obx', 'windows-installer.obx', 'C:\\Program Files\\ObsidianOS Apps', 'windows-installer', '🛡️', 'system', 'Instaladores Windows'],
  ['C:\\Program Files\\ObsidianOS Apps\\kali-tool-center.obx', 'kali-tool-center.obx', 'C:\\Program Files\\ObsidianOS Apps', 'kali-tool-center', '🐉', 'utilities', 'Kali Tool Center'],
  ['C:\\Program Files\\ObsidianOS Apps\\network-inspector.obx', 'network-inspector.obx', 'C:\\Program Files\\ObsidianOS Apps', 'network-inspector', '⌁', 'utilities', 'Network Inspector'],
  ['C:\\Program Files\\ObsidianOS Apps\\wifi-inspector.obx', 'wifi-inspector.obx', 'C:\\Program Files\\ObsidianOS Apps', 'wifi-inspector', '◉', 'utilities', 'Wi‑Fi Inspector'],
  ['C:\\Program Files\\ObsidianOS Apps\\network-shield.obx', 'network-shield.obx', 'C:\\Program Files\\ObsidianOS Apps', 'network-shield', '🛡', 'utilities', 'Network Shield'],
  ['C:\\Program Files\\ObsidianOS Apps\\regedit.obx', 'regedit.obx', 'C:\\Program Files\\ObsidianOS Apps', 'regedit', '🧊', 'system', 'Editor do Registro'],
  ['C:\\Program Files\\ObsidianOS Apps\\ocode.obx', 'ocode.obx', 'C:\\Program Files\\ObsidianOS Apps', 'obsidian-code', '⚡', 'productivity', 'Obsidian Code'],
  ['C:\\Program Files\\ObsidianOS Apps\\obsrecord.obx', 'obsrecord.obx', 'C:\\Program Files\\ObsidianOS Apps', 'obs-record', '🎥', 'multimedia', 'ObS Record'],
  ['C:\\Program Files\\ObsidianOS Apps\\mediaplayer.obx', 'mediaplayer.obx', 'C:\\Program Files\\ObsidianOS Apps', 'media-player', '🎬', 'multimedia', 'Media Player'],
  ['C:\\Program Files\\ObsidianOS Apps\\store.obx', 'store.obx', 'C:\\Program Files\\ObsidianOS Apps', 'obsidian-store', '🏪', 'system', 'Linux App Center'],
];