export const dirs = [
  ['C:', 'C:', '', true],
  ['C:\\ObsidianOS', 'ObsidianOS', 'C:', true],
  ['C:\\ObsidianOS\\System32', 'System32', 'C:\\ObsidianOS', true],
  ['C:\\ObsidianOS\\System32\\drivers', 'drivers', 'C:\\ObsidianOS\\System32', true],
  ['C:\\ObsidianOS\\System32\\config', 'config', 'C:\\ObsidianOS\\System32', true],
  ['C:\\ObsidianOS\\System32\\wbem', 'wbem', 'C:\\ObsidianOS\\System32', true],
  ['C:\\ObsidianOS\\System32\\WindowsPowerShell', 'WindowsPowerShell', 'C:\\ObsidianOS\\System32', true],
  ['C:\\ObsidianOS\\System32\\en-US', 'en-US', 'C:\\ObsidianOS\\System32', true],
  ['C:\\ObsidianOS\\System32\\pt-BR', 'pt-BR', 'C:\\ObsidianOS\\System32', true],
  ['C:\\ObsidianOS\\Fonts', 'Fonts', 'C:\\ObsidianOS', true],
  ['C:\\ObsidianOS\\Temp', 'Temp', 'C:\\ObsidianOS', false],
  ['C:\\ObsidianOS\\Logs', 'Logs', 'C:\\ObsidianOS', false],
  ['C:\\ObsidianOS\\INF', 'INF', 'C:\\ObsidianOS', true],
  ['C:\\ObsidianOS\\SysWOW64', 'SysWOW64', 'C:\\ObsidianOS', true],
  ['C:\\ObsidianOS\\SDK', 'SDK', 'C:\\ObsidianOS', true],
  ['C:\\ObsidianOS\\SDK\\lib', 'lib', 'C:\\ObsidianOS\\SDK', true],
  ['C:\\ObsidianOS\\SDK\\docs', 'docs', 'C:\\ObsidianOS\\SDK', true],
  ['C:\\ObsidianOS\\SDK\\examples', 'examples', 'C:\\ObsidianOS\\SDK', true],
  ['C:\\Program Files', 'Program Files', 'C:', true],
  ['C:\\Program Files\\ObsidianOS Apps', 'ObsidianOS Apps', 'C:\\Program Files', true],
  ['C:\\Program Files (x86)', 'Program Files (x86)', 'C:', true],
  ['C:\\Users', 'Users', 'C:', true],
  ['C:\\Users\\User', 'User', 'C:\\Users', false],
  ['C:\\Users\\User\\Desktop', 'Desktop', 'C:\\Users\\User', false],
  ['C:\\Users\\User\\Documents', 'Documents', 'C:\\Users\\User', false],
  ['C:\\Users\\User\\Downloads', 'Downloads', 'C:\\Users\\User', false],
  ['C:\\Users\\User\\Pictures', 'Pictures', 'C:\\Users\\User', false],
  ['C:\\Users\\User\\Music', 'Music', 'C:\\Users\\User', false],
  ['C:\\Users\\User\\Videos', 'Videos', 'C:\\Users\\User', false],
  ['C:\\Users\\User\\AppData', 'AppData', 'C:\\Users\\User', false],
  ['C:\\Users\\User\\AppData\\Local', 'Local', 'C:\\Users\\User\\AppData', false],
  ['C:\\Users\\User\\AppData\\Local\\Temp', 'Temp', 'C:\\Users\\User\\AppData\\Local', false],
  ['C:\\Users\\User\\AppData\\Roaming', 'Roaming', 'C:\\Users\\User\\AppData', false],
  ['C:\\Users\\Public', 'Public', 'C:\\Users', false],
  ['C:\\ProgramData', 'ProgramData', 'C:', false],
  ['C:\\Recovery', 'Recovery', 'C:', true],
  ['C:\\System Volume Information', 'System Volume Information', 'C:', true],
  ['C:\\System Volume Information\\VSS', 'VSS', 'C:\\System Volume Information', true],
] as const;
