analyzer:
  exclude:
    - build/**
    - windows/flutter/ephemeral/**
    - windows/**
  errors:
    unused_import: error
    dead_code: error

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    use_super_parameters: true
