package cgroups

import (
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"sync"
	"syscall"
	"time"
)

const (
	MinMemoryBytes = 64 * 1024 * 1024
	MaxMemoryBytes = 16 * 1024 * 1024 * 1024
	MinCPUPercent  = 10
	MaxCPUPercent  = 400
	MinPids        = 16
	MaxPids        = 4096
)

type LinuxResourcePolicy struct { MemoryMaxBytes *uint64 `json:"memoryMaxBytes,omitempty"`; MemoryHighBytes *uint64 `json:"memoryHighBytes,omitempty"`; CPUPercent *int `json:"cpuPercent,omitempty"`; PidsMax *int `json:"pidsMax,omitempty"` }
type LinuxCgroupCapabilities struct { Version int `json:"version"`; Mounted bool `json:"mounted"`; CurrentPath string `json:"currentPath"`; ControllersAvailable []string `json:"controllersAvailable"`; ControllersDelegated []string `json:"controllersDelegated"`; WritableFiles map[string]bool `json:"writableFiles"`; ControllerSupport map[string]bool `json:"controllerSupport"`; Systemd bool `json:"systemd"`; ControlEnabled bool `json:"controlEnabled"`; ControlAvailable bool `json:"controlAvailable"`; ReadOnly bool `json:"readOnly"`; Reason string `json:"reason,omitempty"` }
type LinuxCgroupAssignment struct { ID string `json:"id"`; PID int `json:"pid"`; OriginalPath string `json:"originalPath"`; CgroupPath string `json:"cgroupPath"`; Policy LinuxResourcePolicy `json:"policy"`; AppliedAt string `json:"appliedAt"` }
type LinuxResourceMetrics struct { CgroupPath string `json:"cgroupPath"`; MemoryCurrentBytes *uint64 `json:"memoryCurrentBytes,omitempty"`; MemoryMax string `json:"memoryMax,omitempty"`; MemoryHigh string `json:"memoryHigh,omitempty"`; PidsCurrent *uint64 `json:"pidsCurrent,omitempty"`; PidsMax string `json:"pidsMax,omitempty"`; CPUStat map[string]uint64 `json:"cpuStat,omitempty"` }
type Options struct { Root string; ProcRoot string; ControlEnabled bool }
type Manager struct { root string; procRoot string; controlEnabled bool; mu sync.Mutex; assignments map[string]LinuxCgroupAssignment }
type codedError string
func (e codedError) Error() string{return string(e)}; func coded(code string)error{return codedError(code)}
func Code(err error) string { var c codedError; if errors.As(err,&c){return string(c)}; return "INTERNAL_ERROR" }
func NewManager()*Manager{return NewManagerWithOptions(Options{Root:"/sys/fs/cgroup",ProcRoot:"/proc",ControlEnabled:os.Getenv("CLOUDOS_WSL_CORE_CGROUP_CONTROL")=="1"})}
func NewManagerWithOptions(o Options)*Manager{root:=o.Root;if root==""{root="/sys/fs/cgroup"};proc:=o.ProcRoot;if proc==""{proc="/proc"};return &Manager{root:filepath.Clean(root),procRoot:filepath.Clean(proc),controlEnabled:o.ControlEnabled,assignments:map[string]LinuxCgroupAssignment{}}}
func(m *Manager)Capabilities()LinuxCgroupCapabilities{cap:=LinuxCgroupCapabilities{Version:2,WritableFiles:map[string]bool{},ControllerSupport:map[string]bool{},ControlEnabled:m.controlEnabled,ReadOnly:true};if _,err:=os.Stat(filepath.Join(m.root,"cgroup.controllers"));err!=nil{cap.Version=0;cap.Reason="cgroup-v2-not-mounted";return cap};cap.Mounted=true;cap.CurrentPath=readSelfCgroup(m.procRoot);if cap.CurrentPath==""{cap.Reason="current-cgroup-unavailable";return cap};if !safeCgroupPath(cap.CurrentPath){cap.Reason="current-cgroup-invalid";return cap};currentDir,ok:=m.pathFor(cap.CurrentPath);if !ok{cap.Reason="current-cgroup-outside-root";return cap};cap.ControllersAvailable=readWords(filepath.Join(currentDir,"cgroup.controllers"));for _,c:=range readWords(filepath.Join(currentDir,"cgroup.subtree_control")){cap.ControllersDelegated=append(cap.ControllersDelegated,strings.TrimPrefix(c,"+"))};for _,name:=range []string{"cgroup.procs","memory.max","memory.high","cpu.max","pids.max"}{cap.WritableFiles[name]=canOpenWrite(filepath.Join(currentDir,name))};delegated:=setOf(cap.ControllersDelegated);cap.ControllerSupport["memory"]=delegated["memory"]&&cap.WritableFiles["memory.max"]&&cap.WritableFiles["memory.high"];cap.ControllerSupport["cpu"]=delegated["cpu"]&&cap.WritableFiles["cpu.max"];cap.ControllerSupport["pids"]=delegated["pids"]&&cap.WritableFiles["pids.max"];_,e:=os.Stat("/run/systemd/system");cap.Systemd=e==nil;if !m.controlEnabled{cap.Reason="feature-flag-disabled";return cap};if cap.CurrentPath=="/"{cap.Reason="root-cgroup-write-forbidden";return cap};if !dirWritable(currentDir)||!cap.WritableFiles["cgroup.procs"]{cap.Reason="cgroup-not-delegated-writable";return cap};if !cap.ControllerSupport["memory"]&&!cap.ControllerSupport["cpu"]&&!cap.ControllerSupport["pids"]{cap.Reason="controllers-not-safely-delegated";return cap};cap.ControlAvailable=true;cap.ReadOnly=false;cap.Reason="";return cap}
func(m *Manager)Metrics(path string)(LinuxResourceMetrics,error){if path==""{path=readSelfCgroup(m.procRoot)};dir,ok:=m.pathFor(path);if !ok{return LinuxResourceMetrics{},coded("CGROUP_PATH_DENIED")};r:=LinuxResourceMetrics{CgroupPath:path,CPUStat:map[string]uint64{}};if v,ok:=readUint(filepath.Join(dir,"memory.current"));ok{r.MemoryCurrentBytes=&v};r.MemoryMax=readToken(filepath.Join(dir,"memory.max"));r.MemoryHigh=readToken(filepath.Join(dir,"memory.high"));if v,ok:=readUint(filepath.Join(dir,"pids.current"));ok{r.PidsCurrent=&v};r.PidsMax=readToken(filepath.Join(dir,"pids.max"));if raw,err:=os.ReadFile(filepath.Join(dir,"cpu.stat"));err==nil{for _,line:=range strings.Split(string(raw),"\n"){f:=strings.Fields(line);if len(f)==2{if v,e:=strconv.ParseUint(f[1],10,64);e==nil{r.CPUStat[f[0]]=v}}}};return r,nil}
func(m *Manager)Apply(pid int,expectedStart uint64,policy LinuxResourcePolicy)(LinuxCgroupAssignment,error){if pid<=1{return LinuxCgroupAssignment{},coded("PROCESS_PROTECTED")};if !m.controlEnabled{return LinuxCgroupAssignment{},coded("CGROUP_CONTROL_DISABLED")};cap:=m.Capabilities();if !cap.ControlAvailable{return LinuxCgroupAssignment{},coded("CGROUP_CONTROL_UNAVAILABLE")};if err:=validatePolicy(policy,cap);err!=nil{return LinuxCgroupAssignment{},err};if !sameUserProcess(m.procRoot,pid){return LinuxCgroupAssignment{},coded("PROCESS_DENIED")};if expectedStart==0||processStart(m.procRoot,pid)!=expectedStart{return LinuxCgroupAssignment{},coded("PID_REUSED")};original:=readProcessCgroup(m.procRoot,pid);if original==""{return LinuxCgroupAssignment{},coded("PROCESS_NOT_FOUND")};if original!=cap.CurrentPath{return LinuxCgroupAssignment{},coded("CGROUP_PROCESS_OUTSIDE_CORE")};parent,ok:=m.pathFor(cap.CurrentPath);if !ok{return LinuxCgroupAssignment{},coded("CGROUP_PATH_DENIED")};id:=randomID();childName:="cloudos-"+id;child:=filepath.Join(parent,childName);if !strings.HasPrefix(child+string(os.PathSeparator),parent+string(os.PathSeparator)){return LinuxCgroupAssignment{},coded("CGROUP_PATH_DENIED")};if err:=os.Mkdir(child,0750);err!=nil{return LinuxCgroupAssignment{},coded("CGROUP_CREATE_FAILED")};rollback:=func(){_=os.Remove(child)};if err:=writePolicy(child,policy);err!=nil{rollback();return LinuxCgroupAssignment{},err};if processStart(m.procRoot,pid)!=expectedStart||!sameUserProcess(m.procRoot,pid){rollback();return LinuxCgroupAssignment{},coded("PID_REUSED")};if err:=os.WriteFile(filepath.Join(child,"cgroup.procs"),[]byte(strconv.Itoa(pid)),0644);err!=nil{rollback();return LinuxCgroupAssignment{},coded("CGROUP_ASSIGN_FAILED")};a:=LinuxCgroupAssignment{ID:id,PID:pid,OriginalPath:original,CgroupPath:joinCgroup(cap.CurrentPath,childName),Policy:policy,AppliedAt:time.Now().UTC().Format(time.RFC3339Nano)};m.mu.Lock();m.assignments[id]=a;m.mu.Unlock();return a,nil}
func(m *Manager)GetAssignment(id string)(LinuxCgroupAssignment,error){m.mu.Lock();defer m.mu.Unlock();a,ok:=m.assignments[id];if !ok{return LinuxCgroupAssignment{},coded("CGROUP_ASSIGNMENT_NOT_FOUND")};return a,nil}
func(m *Manager)Clear(id string)error{m.mu.Lock();a,ok:=m.assignments[id];if ok{delete(m.assignments,id)};m.mu.Unlock();if !ok{return coded("CGROUP_ASSIGNMENT_NOT_FOUND")};return m.rollback(a)}
func(m *Manager)Close(){m.mu.Lock();all:=make([]LinuxCgroupAssignment,0,len(m.assignments));for _,a:=range m.assignments{all=append(all,a)};m.assignments=map[string]LinuxCgroupAssignment{};m.mu.Unlock();for _,a:=range all{_=m.rollback(a)}}
func(m *Manager)rollback(a LinuxCgroupAssignment)error{target,ok:=m.pathFor(a.CgroupPath);if !ok{return coded("CGROUP_PATH_DENIED")};original,ok:=m.pathFor(a.OriginalPath);if !ok{return coded("CGROUP_PATH_DENIED")};if readProcessCgroup(m.procRoot,a.PID)==a.CgroupPath{_=os.WriteFile(filepath.Join(original,"cgroup.procs"),[]byte(strconv.Itoa(a.PID)),0644)};if err:=os.Remove(target);err!=nil&&!errors.Is(err,os.ErrNotExist){return coded("CGROUP_CLEANUP_FAILED")};return nil}
func validatePolicy(p LinuxResourcePolicy,c LinuxCgroupCapabilities)error{if p.MemoryMaxBytes==nil&&p.MemoryHighBytes==nil&&p.CPUPercent==nil&&p.PidsMax==nil{return coded("CGROUP_POLICY_EMPTY")};if p.MemoryMaxBytes!=nil{if !c.ControllerSupport["memory"]||*p.MemoryMaxBytes<MinMemoryBytes||*p.MemoryMaxBytes>MaxMemoryBytes{return coded("CGROUP_POLICY_INVALID")}};if p.MemoryHighBytes!=nil{if !c.ControllerSupport["memory"]||*p.MemoryHighBytes<MinMemoryBytes||*p.MemoryHighBytes>MaxMemoryBytes{return coded("CGROUP_POLICY_INVALID")};if p.MemoryMaxBytes!=nil&&*p.MemoryHighBytes>*p.MemoryMaxBytes{return coded("CGROUP_POLICY_INVALID")}};if p.CPUPercent!=nil{if !c.ControllerSupport["cpu"]||*p.CPUPercent<MinCPUPercent||*p.CPUPercent>MaxCPUPercent{return coded("CGROUP_POLICY_INVALID")}};if p.PidsMax!=nil{if !c.ControllerSupport["pids"]||*p.PidsMax<MinPids||*p.PidsMax>MaxPids{return coded("CGROUP_POLICY_INVALID")}};return nil}
func writePolicy(dir string,p LinuxResourcePolicy)error{if p.MemoryMaxBytes!=nil{if err:=writeLimit(filepath.Join(dir,"memory.max"),strconv.FormatUint(*p.MemoryMaxBytes,10));err!=nil{return err}};if p.MemoryHighBytes!=nil{if err:=writeLimit(filepath.Join(dir,"memory.high"),strconv.FormatUint(*p.MemoryHighBytes,10));err!=nil{return err}};if p.CPUPercent!=nil{quota:=*p.CPUPercent*1000;if err:=writeLimit(filepath.Join(dir,"cpu.max"),fmt.Sprintf("%d 100000",quota));err!=nil{return err}};if p.PidsMax!=nil{if err:=writeLimit(filepath.Join(dir,"pids.max"),strconv.Itoa(*p.PidsMax));err!=nil{return err}};return nil}
func writeLimit(path,value string)error{if err:=os.WriteFile(path,[]byte(value),0644);err!=nil{return coded("CGROUP_WRITE_FAILED")};return nil}
func(m *Manager)pathFor(cgroup string)(string,bool){if !safeCgroupPath(cgroup){return "",false};rel:=strings.TrimPrefix(filepath.Clean(cgroup),string(os.PathSeparator));candidate:=filepath.Join(m.root,rel);root:=m.root+string(os.PathSeparator);if candidate!=m.root&&!strings.HasPrefix(candidate+string(os.PathSeparator),root){return "",false};return candidate,true}
func safeCgroupPath(p string)bool{return strings.HasPrefix(p,"/")&&!strings.Contains(p,"\x00")&&filepath.Clean(p)==p&&!strings.Contains(p,"..")}
func joinCgroup(parent,child string)string{if parent=="/"{return "/"+child};return strings.TrimRight(parent,"/")+"/"+child}
func readSelfCgroup(proc string)string{return readCgroupFile(filepath.Join(proc,"self","cgroup"))};func readProcessCgroup(proc string,pid int)string{return readCgroupFile(filepath.Join(proc,strconv.Itoa(pid),"cgroup"))}
func readCgroupFile(path string)string{raw,err:=os.ReadFile(path);if err!=nil{return ""};for _,line:=range strings.Split(string(raw),"\n"){if strings.HasPrefix(line,"0::"){p:=strings.TrimSpace(strings.TrimPrefix(line,"0::"));if safeCgroupPath(p){return p}}};return ""}
func readWords(path string)[]string{raw,err:=os.ReadFile(path);if err!=nil{return nil};return strings.Fields(string(raw))}
func readToken(path string)string{raw,err:=os.ReadFile(path);if err!=nil{return ""};value:=strings.TrimSpace(string(raw));if len(value)>64{return ""};return value}
func readUint(path string)(uint64,bool){v:=readToken(path);if v==""||v=="max"{return 0,false};n,e:=strconv.ParseUint(v,10,64);return n,e==nil}
func canOpenWrite(path string)bool{f,err:=os.OpenFile(path,os.O_WRONLY,0);if err!=nil{return false};_=f.Close();return true};func dirWritable(path string)bool{return syscall.Access(path,2)==nil}
func setOf(values []string)map[string]bool{m:=map[string]bool{};for _,v:=range values{m[strings.TrimPrefix(v,"+")]=true};return m}
func sameUserProcess(proc string,pid int)bool{raw,err:=os.ReadFile(filepath.Join(proc,strconv.Itoa(pid),"status"));if err!=nil{return false};for _,line:=range strings.Split(string(raw),"\n"){if strings.HasPrefix(line,"Uid:"){f:=strings.Fields(line);if len(f)>1{uid,_:=strconv.Atoi(f[1]);return uid==os.Geteuid()}}};return false}
func processStart(proc string,pid int)uint64{raw,err:=os.ReadFile(filepath.Join(proc,strconv.Itoa(pid),"stat"));if err!=nil{return 0};text:=strings.TrimSpace(string(raw));close:=strings.LastIndex(text,") ");if close<0{return 0};f:=strings.Fields(text[close+2:]);if len(f)<20{return 0};v,_:=strconv.ParseUint(f[19],10,64);return v}
func randomID()string{b:=make([]byte,8);if _,err:=rand.Read(b);err!=nil{return strconv.FormatInt(time.Now().UnixNano(),16)};return hex.EncodeToString(b)}
