namespace CloudOS.Host.Native;

/// <summary>
/// Defines the fail-closed contract between the backend catalog launcher and the
/// Windows host. Only host-created direct launch Jobs whose UI can be attributed
/// to their bounded member processes are admitted. Protocol/UWP launches and
/// shared brokers cannot satisfy that contract and must be unavailable.
/// </summary>
public static class NativeLaunchContainmentPolicy
{
    // Real desktop applications frequently bootstrap through helpers, splash screens,
    // updaters or child processes before their stable top-level HWND exists. Keep the
    // launch capability quarantined while that happens instead of killing the Job on
    // an aggressive UI-startup deadline. These are upper bounds, not fixed sleeps.
    public const int WindowCorrelationTimeoutMilliseconds = 20_000;
    public const int PendingAttachTimeoutMilliseconds = 30_000;
    public const int GracefulCloseTimeoutMilliseconds = 1_000;
    public const int PrimaryWindowMinimumWidth = 240;
    public const int PrimaryWindowMinimumHeight = 120;
    public const long DominantWindowAreaRatio = 4;

    private static readonly HashSet<string> DirectLaunchKinds = new(StringComparer.Ordinal)
    {
        "windows-executable",
        // The backend may resolve a verified .lnk target and start that target directly.
        // A regular shell/Start-Process shortcut launch is brokerable and is not admitted.
        "windows-shortcut-direct",
        // The backend may convert the Windows shortcut argument tail into a bounded argv
        // vector using the standard backslash/quote grammar. The Host still starts the
        // exact target executable directly; no cmd, PowerShell or ShellExecute path exists.
        "windows-shortcut-argv",
        // A verified .bat/.cmd target may run through hidden System32 cmd.exe inside the
        // same Job so GUI descendants remain attributable to the CloudOS launch capability.
        "windows-script-direct"
    };

    private static readonly HashSet<string> SharedBrokerProcessNames = new(StringComparer.OrdinalIgnoreCase)
    {
        "applicationframehost",
        "dwm",
        "explorer",
        "msrdc",
        "mstsc",
        "runtimebroker",
        "shellexperiencehost",
        "startmenuexperiencehost",
        "wsl",
        "wslg",
        "wslhost",
        "wslservice"
    };

    public static NativeLaunchAdmission EvaluateLaunchKind(string? launchKind)
    {
        if (string.IsNullOrWhiteSpace(launchKind) || !DirectLaunchKinds.Contains(launchKind))
        {
            return NativeLaunchAdmission.Deny(
                "APP_LAUNCH_KIND_UNSUPPORTED",
                "Este tipo de aplicativo usa protocolo, UWP ou broker e não pode ser correlacionado com segurança.");
        }

        return NativeLaunchAdmission.Allow();
    }

    public static bool IsSharedBroker(string? processName) =>
        !string.IsNullOrWhiteSpace(processName) && SharedBrokerProcessNames.Contains(processName);

    /// <summary>
    /// The backend only emits windows-shortcut-argv after it has converted a bounded,
    /// syntactically complete shortcut argument tail into explicit argv entries. Regular
    /// shortcut-direct remains argument-free. Script descriptors are generated by the
    /// trusted backend as an exact six-item argv vector:
    /// /d /s /v:off /c call absolute-script-path. The fixed CALL token prevents cmd.exe
    /// from stripping the only quote pair around a script path that contains spaces.
    /// </summary>
    public static bool AllowsArgumentVector(string? launchKind, int argumentCount) =>
        argumentCount >= 0
        && (string.Equals(launchKind, "windows-executable", StringComparison.Ordinal)
            || (string.Equals(launchKind, "windows-shortcut-direct", StringComparison.Ordinal)
                && argumentCount == 0)
            || (string.Equals(launchKind, "windows-shortcut-argv", StringComparison.Ordinal)
                && argumentCount > 0)
            || (string.Equals(launchKind, "windows-script-direct", StringComparison.Ordinal)
                && argumentCount == 6));

    /// <summary>
    /// Tracking a Job member PID is necessary but not sufficient. Public managed=true
    /// is allowed only after a concrete top-level HWND from that exact member has
    /// been observed and quarantined by NativeWindowManager.
    /// </summary>
    public static bool CanReportManaged(bool processTracked, bool hasTrackableWindow, bool sharedBroker) =>
        processTracked && hasTrackableWindow && !sharedBroker;

    /// <summary>
    /// Selects a primary surface without using enumeration order, focus, or timing as
    /// authority. A single real application surface may coexist with small helper HWNDs.
    /// Two plausible application surfaces remain ambiguous and are rejected fail-closed.
    /// Sorting is used only to compare geometry; enumeration order is never launch authority.
    /// </summary>
    public static NativeWindowCandidateSelection SelectUniqueQuarantinedWindow(
        IReadOnlyList<NativeWindowSnapshot> candidates,
        out NativeWindowSnapshot? selected)
    {
        ArgumentNullException.ThrowIfNull(candidates);
        selected = null;
        if (candidates.Count == 0) return NativeWindowCandidateSelection.None;
        if (candidates.Count == 1)
        {
            selected = candidates[0];
            return NativeWindowCandidateSelection.Unique;
        }

        var plausible = candidates
            .Where(IsPlausiblePrimarySurface)
            .OrderByDescending(WindowArea)
            .ToArray();

        if (plausible.Length > 1)
        {
            var titled = plausible.Where(candidate => !string.IsNullOrWhiteSpace(candidate.Title)).ToArray();
            if (titled.Length != 1) return NativeWindowCandidateSelection.Ambiguous;
            selected = titled[0];
            return NativeWindowCandidateSelection.Unique;
        }

        if (plausible.Length != 1) return NativeWindowCandidateSelection.Ambiguous;

        var primary = plausible[0];
        var largestAuxiliaryArea = candidates
            .Where(candidate => candidate.Handle != primary.Handle)
            .Select(WindowArea)
            .DefaultIfEmpty(0)
            .Max();
        if (largestAuxiliaryArea > 0
            && WindowArea(primary) < largestAuxiliaryArea * DominantWindowAreaRatio)
            return NativeWindowCandidateSelection.Ambiguous;

        selected = primary;
        return NativeWindowCandidateSelection.Unique;
    }

    public static bool IsPlausiblePrimarySurface(NativeWindowSnapshot candidate) =>
        candidate.Bounds.Width >= PrimaryWindowMinimumWidth
        && candidate.Bounds.Height >= PrimaryWindowMinimumHeight;

    private static long WindowArea(NativeWindowSnapshot candidate) =>
        Math.Max(0L, (long)candidate.Bounds.Width) * Math.Max(0L, candidate.Bounds.Height);

    /// <summary>
    /// Every failure after a process was launched is terminal. Restoring an
    /// attached window to the desktop would be an external-window fallback.
    /// </summary>
    public static bool RequiresTermination(NativeContainmentFailure failure) => failure is
        NativeContainmentFailure.WindowCorrelationTimeout or
        NativeContainmentFailure.QuarantineFailed or
        NativeContainmentFailure.AmbiguousWindow or
        NativeContainmentFailure.AttachFailed or
        NativeContainmentFailure.LayoutFailed or
        NativeContainmentFailure.AttachmentLost or
        NativeContainmentFailure.PendingAttachExpired or
        NativeContainmentFailure.DetachRequested or
        NativeContainmentFailure.GracefulCloseFailed or
        NativeContainmentFailure.DocumentReset or
        NativeContainmentFailure.HostDisposed;
}

public sealed class NativeLaunchAdmission
{
    private NativeLaunchAdmission(bool allowed, string? errorCode, string? message)
    {
        Allowed = allowed;
        ErrorCode = errorCode;
        Message = message;
    }

    public bool Allowed { get; }
    public string? ErrorCode { get; }
    public string? Message { get; }

    public static NativeLaunchAdmission Allow() => new(true, null, null);
    public static NativeLaunchAdmission Deny(string errorCode, string message) => new(false, errorCode, message);
}

public enum NativeWindowCandidateSelection
{
    None,
    Unique,
    Ambiguous
}

public enum NativeContainmentFailure
{
    WindowCorrelationTimeout,
    QuarantineFailed,
    AmbiguousWindow,
    AttachFailed,
    LayoutFailed,
    AttachmentLost,
    PendingAttachExpired,
    DetachRequested,
    GracefulCloseFailed,
    DocumentReset,
    HostDisposed
}
