#include "native_process_window.h"
#include <commctrl.h>
#include <psapi.h>
#include <tlhelp32.h>
#include <algorithm>
#include <array>
#include <cwchar>
#include <new>
#include <utility>
#pragma comment(lib,"comctl32.lib")
#pragma comment(lib,"psapi.lib")
namespace{constexpr wchar_t kClass[]=L"CloudOS.Native.Processes.v1";constexpr int ID_LIST=1101,ID_REFRESH=1102,ID_KILL=1103,ID_FOCUS=1104;bool Register(HINSTANCE h){WNDCLASSEXW w{sizeof(w)};w.lpfnWndProc=&CloudOSNativeProcessWindow::WindowProcedure;w.hInstance=h;w.hCursor=LoadCursorW(nullptr,IDC_ARROW);w.hbrBackground=reinterpret_cast<HBRUSH>(COLOR_WINDOW+1);w.lpszClassName=kClass;return RegisterClassExW(&w)!=0||GetLastError()==ERROR_CLASS_ALREADY_EXISTS;}struct FindCtx{DWORD pid;HWND found;};BOOL CALLBACK FindMain(HWND h,LPARAM p){auto*c=reinterpret_cast<FindCtx*>(p);DWORD pid=0;GetWindowThreadProcessId(h,&pid);if(pid==c->pid&&IsWindowVisible(h)&&GetWindow(h,GW_OWNER)==nullptr){c->found=h;return FALSE;}return TRUE;}}
CloudOSNativeProcessWindow::CloudOSNativeProcessWindow(HINSTANCE i):instance_(i){}
void CloudOSNativeProcessWindow::Open(HINSTANCE i){auto*p=new(std::nothrow)CloudOSNativeProcessWindow(i);if(!p||!p->Create()){delete p;MessageBoxW(nullptr,L"Nao foi possivel abrir Processos.",L"CloudOS",MB_OK|MB_ICONERROR);}}
bool CloudOSNativeProcessWindow::Create(){if(!Register(instance_))return false;window_=CreateWindowExW(WS_EX_APPWINDOW,kClass,L"Processos - CloudOS",WS_OVERLAPPEDWINDOW,CW_USEDEFAULT,CW_USEDEFAULT,860,580,nullptr,nullptr,instance_,this);if(!window_)return false;list_=CreateWindowExW(WS_EX_CLIENTEDGE,WC_LISTVIEWW,L"",WS_CHILD|WS_VISIBLE|LVS_REPORT|LVS_SINGLESEL,0,0,0,0,window_,reinterpret_cast<HMENU>(ID_LIST),instance_,nullptr);ListView_SetExtendedListViewStyle(list_,LVS_EX_FULLROWSELECT|LVS_EX_DOUBLEBUFFER);LVCOLUMNW col{LVCF_TEXT|LVCF_WIDTH};col.cx=90;col.pszText=const_cast<wchar_t*>(L"PID");ListView_InsertColumn(list_,0,&col);col.cx=430;col.pszText=const_cast<wchar_t*>(L"Processo");ListView_InsertColumn(list_,1,&col);col.cx=140;col.pszText=const_cast<wchar_t*>(L"Memoria");ListView_InsertColumn(list_,2,&col);refresh_button_=CreateWindowW(L"BUTTON",L"Atualizar",WS_CHILD|WS_VISIBLE,0,0,0,0,window_,reinterpret_cast<HMENU>(ID_REFRESH),instance_,nullptr);terminate_button_=CreateWindowW(L"BUTTON",L"Encerrar",WS_CHILD|WS_VISIBLE,0,0,0,0,window_,reinterpret_cast<HMENU>(ID_KILL),instance_,nullptr);focus_button_=CreateWindowW(L"BUTTON",L"Focar janela",WS_CHILD|WS_VISIBLE,0,0,0,0,window_,reinterpret_cast<HMENU>(ID_FOCUS),instance_,nullptr);SetTimer(window_,1,2000,nullptr);Refresh();ShowWindow(window_,SW_SHOW);return true;}
void CloudOSNativeProcessWindow::Layout(){RECT r{};GetClientRect(window_,&r);int w=r.right,int h=r.bottom;MoveWindow(list_,12,12,max(100,w-24),max(100,h-66),TRUE);MoveWindow(refresh_button_,12,max(12,h-44),100,30,TRUE);MoveWindow(focus_button_,122,max(12,h-44),120,30,TRUE);MoveWindow(terminate_button_,252,max(12,h-44),100,30,TRUE);}
SIZE_T CloudOSNativeProcessWindow::QueryWorkingSet(DWORD pid){HANDLE p=OpenProcess(PROCESS_QUERY_LIMITED_INFORMATION|PROCESS_VM_READ,FALSE,pid);if(!p)return 0;PROCESS_MEMORY_COUNTERS pmc{};SIZE_T v=GetProcessMemoryInfo(p,&pmc,sizeof(pmc))?pmc.WorkingSetSize:0;CloseHandle(p);return v;}
std::wstring CloudOSNativeProcessWindow::FormatMemory(SIZE_T b){wchar_t t[64]{};double m=static_cast<double>(b)/(1024.0*1024.0);swprintf_s(t,L"%.1f MB",m);return t;}
void CloudOSNativeProcessWindow::Refresh(){processes_.clear();HANDLE s=CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS,0);if(s==INVALID_HANDLE_VALUE)return;PROCESSENTRY32W pe{sizeof(pe)};if(Process32FirstW(s,&pe)){do{ProcessEntry e{};e.process_id=pe.th32ProcessID;e.name=pe.szExeFile;e.working_set=QueryWorkingSet(e.process_id);processes_.push_back(std::move(e));}while(Process32NextW(s,&pe));}CloseHandle(s);std::sort(processes_.begin(),processes_.end(),[](auto&a,auto&b){return a.working_set>b.working_set;});ListView_DeleteAllItems(list_);for(size_t i=0;i<processes_.size();++i){wchar_t pid[32]{};swprintf_s(pid,L"%lu",processes_[i].process_id);LVITEMW item{};item.mask=LVIF_TEXT;item.iItem=static_cast<int>(i);item.pszText=pid;ListView_InsertItem(list_,&item);ListView_SetItemText(list_,static_cast<int>(i),1,processes_[i].name.data());auto mem=FormatMemory(processes_[i].working_set);ListView_SetItemText(list_,static_cast<int>(i),2,mem.data());}}
void CloudOSNativeProcessWindow::TerminateSelected(){int i=ListView_GetNextItem(list_,-1,LVNI_SELECTED);if(i<0||static_cast<size_t>(i)>=processes_.size())return;DWORD pid=processes_[static_cast<size_t>(i)].process_id;if(pid==GetCurrentProcessId()){MessageBoxW(window_,L"Use Sair do CloudOS para encerrar o shell.",L"CloudOS",MB_OK);return;}if(MessageBoxW(window_,L"Encerrar o processo selecionado?",L"CloudOS",MB_YESNO|MB_ICONWARNING)!=IDYES)return;HANDLE p=OpenProcess(PROCESS_TERMINATE,FALSE,pid);if(p){TerminateProcess(p,1);CloseHandle(p);}Refresh();}
void CloudOSNativeProcessWindow::FocusSelectedProcess(){int i=ListView_GetNextItem(list_,-1,LVNI_SELECTED);if(i<0||static_cast<size_t>(i)>=processes_.size())return;FindCtx c{processes_[static_cast<size_t>(i)].process_id,nullptr};EnumWindows(&FindMain,reinterpret_cast<LPARAM>(&c));if(c.found){if(IsIconic(c.found))ShowWindow(c.found,SW_RESTORE);SetForegroundWindow(c.found);}}
LRESULT CloudOSNativeProcessWindow::HandleMessage(UINT m,WPARAM w,LPARAM l){switch(m){case WM_SIZE:Layout();return 0;case WM_TIMER:Refresh();return 0;case WM_COMMAND:switch(LOWORD(w)){case ID_REFRESH:Refresh();return 0;case ID_KILL:TerminateSelected();return 0;case ID_FOCUS:FocusSelectedProcess();return 0;}break;case WM_CLOSE:DestroyWindow(window_);return 0;case WM_NCDESTROY:KillTimer(window_,1);window_=nullptr;delete this;return 0;}return DefWindowProcW(window_,m,w,l);}
LRESULT CALLBACK CloudOSNativeProcessWindow::WindowProcedure(HWND h,UINT m,WPARAM w,LPARAM l){auto*p=m==WM_NCCREATE?static_cast<CloudOSNativeProcessWindow*>(reinterpret_cast<CREATESTRUCTW*>(l)->lpCreateParams):reinterpret_cast<CloudOSNativeProcessWindow*>(GetWindowLongPtrW(h,GWLP_USERDATA));if(m==WM_NCCREATE&&p){p->window_=h;SetWindowLongPtrW(h,GWLP_USERDATA,reinterpret_cast<LONG_PTR>(p));}return p?p->HandleMessage(m,w,l):DefWindowProcW(h,m,w,l);}
