#include "native_apps_window.h"
#include <commctrl.h>
#include <knownfolders.h>
#include <shellapi.h>
#include <shlobj.h>
#include <algorithm>
#include <array>
#include <cwctype>
#include <new>
#include <utility>
#pragma comment(lib,"comctl32.lib")
#pragma comment(lib,"shell32.lib")
namespace{constexpr wchar_t kClass[]=L"CloudOS.Native.Apps.v1";constexpr int ID_SEARCH=1301,ID_LIST=1302,ID_LAUNCH=1303;bool Register(HINSTANCE h){WNDCLASSEXW w{sizeof(w)};w.lpfnWndProc=&CloudOSNativeAppsWindow::WindowProcedure;w.hInstance=h;w.hCursor=LoadCursorW(nullptr,IDC_ARROW);w.hbrBackground=reinterpret_cast<HBRUSH>(COLOR_WINDOW+1);w.lpszClassName=kClass;return RegisterClassExW(&w)!=0||GetLastError()==ERROR_CLASS_ALREADY_EXISTS;}std::wstring FileNameNoExt(std::wstring s){size_t slash=s.find_last_of(L"\\/");if(slash!=std::wstring::npos)s=s.substr(slash+1);size_t dot=s.find_last_of(L'.');if(dot!=std::wstring::npos)s.resize(dot);return s;}bool HasExt(const std::wstring&p,const wchar_t*e){size_t n=wcslen(e);return p.size()>=n&&_wcsicmp(p.c_str()+p.size()-n,e)==0;}}
CloudOSNativeAppsWindow::CloudOSNativeAppsWindow(HINSTANCE i):instance_(i){}
void CloudOSNativeAppsWindow::Open(HINSTANCE i){auto*p=new(std::nothrow)CloudOSNativeAppsWindow(i);if(!p||!p->Create()){delete p;MessageBoxW(nullptr,L"Nao foi possivel abrir Aplicativos.",L"CloudOS",MB_OK|MB_ICONERROR);}}
bool CloudOSNativeAppsWindow::Create(){if(!Register(instance_))return false;window_=CreateWindowExW(WS_EX_APPWINDOW,kClass,L"Aplicativos - CloudOS",WS_OVERLAPPEDWINDOW,CW_USEDEFAULT,CW_USEDEFAULT,820,600,nullptr,nullptr,instance_,this);if(!window_)return false;search_edit_=CreateWindowExW(WS_EX_CLIENTEDGE,L"EDIT",L"",WS_CHILD|WS_VISIBLE|ES_AUTOHSCROLL,0,0,0,0,window_,reinterpret_cast<HMENU>(ID_SEARCH),instance_,nullptr);SendMessageW(search_edit_,EM_SETCUEBANNER,TRUE,reinterpret_cast<LPARAM>(L"Pesquisar aplicativos..."));list_=CreateWindowExW(WS_EX_CLIENTEDGE,WC_LISTVIEWW,L"",WS_CHILD|WS_VISIBLE|LVS_REPORT|LVS_SINGLESEL,0,0,0,0,window_,reinterpret_cast<HMENU>(ID_LIST),instance_,nullptr);ListView_SetExtendedListViewStyle(list_,LVS_EX_FULLROWSELECT|LVS_EX_DOUBLEBUFFER);LVCOLUMNW c{LVCF_TEXT|LVCF_WIDTH};c.cx=300;c.pszText=const_cast<wchar_t*>(L"Aplicativo");ListView_InsertColumn(list_,0,&c);c.cx=430;c.pszText=const_cast<wchar_t*>(L"Origem");ListView_InsertColumn(list_,1,&c);launch_button_=CreateWindowW(L"BUTTON",L"Abrir",WS_CHILD|WS_VISIBLE|BS_DEFPUSHBUTTON,0,0,0,0,window_,reinterpret_cast<HMENU>(ID_LAUNCH),instance_,nullptr);LoadCatalog();ApplyFilter();ShowWindow(window_,SW_SHOW);SetFocus(search_edit_);return true;}
void CloudOSNativeAppsWindow::Layout(){RECT r{};GetClientRect(window_,&r);int w=r.right,h=r.bottom;MoveWindow(search_edit_,12,12,max(100,w-126),30,TRUE);MoveWindow(launch_button_,max(12,w-102),12,90,30,TRUE);MoveWindow(list_,12,52,max(100,w-24),max(80,h-64),TRUE);}
std::wstring CloudOSNativeAppsWindow::ReadText(HWND e){int n=GetWindowTextLengthW(e);std::wstring s(static_cast<size_t>(n)+1,L'\0');if(n>0){GetWindowTextW(e,s.data(),n+1);s.resize(static_cast<size_t>(n));}else s.clear();return s;}
bool CloudOSNativeAppsWindow::ContainsInsensitive(std::wstring_view t,std::wstring_view q){if(q.empty())return true;std::wstring a(t),b(q);std::transform(a.begin(),a.end(),a.begin(),towlower);std::transform(b.begin(),b.end(),b.begin(),towlower);return a.find(b)!=std::wstring::npos;}
void CloudOSNativeAppsWindow::EnumerateFolder(const std::wstring&folder,int depth){if(depth>12)return;WIN32_FIND_DATAW fd{};std::wstring pat=folder+(folder.empty()||folder.back()==L'\\'?L"*":L"\\*");HANDLE h=FindFirstFileW(pat.c_str(),&fd);if(h==INVALID_HANDLE_VALUE)return;do{if(wcscmp(fd.cFileName,L".")==0||wcscmp(fd.cFileName,L"..")==0)continue;std::wstring p=folder+(folder.empty()||folder.back()==L'\\'?L"":L"\\")+fd.cFileName;if(fd.dwFileAttributes&FILE_ATTRIBUTE_DIRECTORY){EnumerateFolder(p,depth+1);}else if(HasExt(p,L".lnk")||HasExt(p,L".url")||HasExt(p,L".exe")){catalog_.push_back({FileNameNoExt(fd.cFileName),p});}}while(FindNextFileW(h,&fd));FindClose(h);}
void CloudOSNativeAppsWindow::LoadCatalog(){catalog_.clear();for(auto id:{FOLDERID_Programs,FOLDERID_CommonPrograms}){PWSTR p=nullptr;if(SUCCEEDED(SHGetKnownFolderPath(id,KF_FLAG_DEFAULT,nullptr,&p))&&p){EnumerateFolder(p,0);CoTaskMemFree(p);}}std::array<wchar_t,MAX_PATH> sys{};if(GetSystemDirectoryW(sys.data(),static_cast<UINT>(sys.size()))>0){for(auto n:{L"cmd.exe",L"notepad.exe",L"taskmgr.exe",L"control.exe"}){std::wstring p=sys.data();p+=L"\\";p+=n;if(GetFileAttributesW(p.c_str())!=INVALID_FILE_ATTRIBUTES)catalog_.push_back({FileNameNoExt(n),p});}}std::sort(catalog_.begin(),catalog_.end(),[](auto&a,auto&b){return _wcsicmp(a.name.c_str(),b.name.c_str())<0;});catalog_.erase(std::unique(catalog_.begin(),catalog_.end(),[](auto&a,auto&b){return _wcsicmp(a.path.c_str(),b.path.c_str())==0;}),catalog_.end());}
void CloudOSNativeAppsWindow::ApplyFilter(){auto q=ReadText(search_edit_);visible_indices_.clear();ListView_DeleteAllItems(list_);for(size_t i=0;i<catalog_.size();++i){if(!ContainsInsensitive(catalog_[i].name,q)&&!ContainsInsensitive(catalog_[i].path,q))continue;visible_indices_.push_back(i);int row=static_cast<int>(visible_indices_.size()-1);LVITEMW item{};item.mask=LVIF_TEXT;item.iItem=row;item.pszText=catalog_[i].name.data();ListView_InsertItem(list_,&item);ListView_SetItemText(list_,row,1,catalog_[i].path.data());}}
void CloudOSNativeAppsWindow::LaunchSelection(){int row=ListView_GetNextItem(list_,-1,LVNI_SELECTED);if(row<0||static_cast<size_t>(row)>=visible_indices_.size())return;auto&app=catalog_[visible_indices_[static_cast<size_t>(row)]];auto h=ShellExecuteW(window_,L"open",app.path.c_str(),nullptr,nullptr,SW_SHOWNORMAL);if(reinterpret_cast<INT_PTR>(h)<=32)MessageBoxW(window_,L"O aplicativo nao pode ser iniciado.",L"CloudOS",MB_OK|MB_ICONERROR);}
LRESULT CloudOSNativeAppsWindow::HandleMessage(UINT m,WPARAM w,LPARAM l){switch(m){case WM_SIZE:Layout();return 0;case WM_COMMAND:if(LOWORD(w)==ID_SEARCH&&HIWORD(w)==EN_CHANGE){ApplyFilter();return 0;}if(LOWORD(w)==ID_LAUNCH){LaunchSelection();return 0;}break;case WM_NOTIFY:{auto*h=reinterpret_cast<NMHDR*>(l);if(h&&h->hwndFrom==list_&&h->code==NM_DBLCLK){LaunchSelection();return 0;}}break;case WM_CLOSE:DestroyWindow(window_);return 0;case WM_NCDESTROY:window_=nullptr;delete this;return 0;}return DefWindowProcW(window_,m,w,l);}
LRESULT CALLBACK CloudOSNativeAppsWindow::WindowProcedure(HWND h,UINT m,WPARAM w,LPARAM l){auto*p=m==WM_NCCREATE?static_cast<CloudOSNativeAppsWindow*>(reinterpret_cast<CREATESTRUCTW*>(l)->lpCreateParams):reinterpret_cast<CloudOSNativeAppsWindow*>(GetWindowLongPtrW(h,GWLP_USERDATA));if(m==WM_NCCREATE&&p){p->window_=h;SetWindowLongPtrW(h,GWLP_USERDATA,reinterpret_cast<LONG_PTR>(p));}return p?p->HandleMessage(m,w,l):DefWindowProcW(h,m,w,l);}
