#include "native_terminal_window.h"
#include "cloudos_native_runtime.h"
#include <dwmapi.h>
#include <algorithm>
#include <array>
#include <cstddef>
#include <new>
#include <string_view>
#include <utility>
#pragma comment(lib,"dwmapi.lib")
namespace{constexpr wchar_t kClass[]=L"CloudOS.Native.Terminal.v1";constexpr UINT WM_OUTPUT=WM_APP+0x330;constexpr size_t MAX_SCROLL=200000;bool Register(HINSTANCE h){WNDCLASSEXW w{sizeof(w)};w.style=CS_HREDRAW|CS_VREDRAW;w.lpfnWndProc=&CloudOSNativeTerminalWindow::WindowProcedure;w.hInstance=h;w.hCursor=LoadCursorW(nullptr,IDC_IBEAM);w.hIcon=LoadIconW(nullptr,IDI_APPLICATION);w.lpszClassName=kClass;return RegisterClassExW(&w)!=0||GetLastError()==ERROR_CLASS_ALREADY_EXISTS;}std::string ToUtf8(std::wstring_view s){if(s.empty())return{};int n=WideCharToMultiByte(CP_UTF8,0,s.data(),static_cast<int>(s.size()),nullptr,0,nullptr,nullptr);if(n<=0)return{};std::string r(static_cast<size_t>(n),'\0');WideCharToMultiByte(CP_UTF8,0,s.data(),static_cast<int>(s.size()),r.data(),n,nullptr,nullptr);return r;}}
CloudOSNativeTerminalWindow::CloudOSNativeTerminalWindow(HINSTANCE i,std::wstring c,std::wstring t):instance_(i),command_line_(std::move(c)),title_(std::move(t)){}
CloudOSNativeTerminalWindow::~CloudOSNativeTerminalWindow(){StopTerminal();if(font_)DeleteObject(font_);}
void CloudOSNativeTerminalWindow::Open(HINSTANCE i,const std::wstring& c,const std::wstring& t){auto*p=new(std::nothrow)CloudOSNativeTerminalWindow(i,c,t);if(!p||!p->Create()){DWORD e=GetLastError();delete p;wchar_t b[200]{};swprintf_s(b,L"Terminal nativo nao iniciou. Win32=%lu",e);MessageBoxW(nullptr,b,L"CloudOS Terminal",MB_OK|MB_ICONERROR);}}
bool CloudOSNativeTerminalWindow::Create(){if(!Register(instance_))return false;window_=CreateWindowExW(WS_EX_APPWINDOW,kClass,title_.c_str(),WS_OVERLAPPEDWINDOW,CW_USEDEFAULT,CW_USEDEFAULT,980,640,nullptr,nullptr,instance_,this);if(!window_)return false;BOOL dark=TRUE;DWORD attr=20;(void)DwmSetWindowAttribute(window_,attr,&dark,sizeof(dark));UpdateFontMetrics();if(!StartTerminal()){DWORD e=GetLastError();DestroyWindow(window_);window_=nullptr;SetLastError(e);return false;}ShowWindow(window_,SW_SHOW);UpdateWindow(window_);SetFocus(window_);return true;}
bool CloudOSNativeTerminalWindow::StartTerminal(){RECT r{};GetClientRect(window_,&r);SHORT cols=static_cast<SHORT>(std::clamp((r.right-r.left)/std::max(1,cell_width_),20,240));SHORT rows=static_cast<SHORT>(std::clamp((r.bottom-r.top)/std::max(1,cell_height_),5,120));if(!cloudos_native_terminal_create(command_line_.c_str(),nullptr,cols,rows,&terminal_,&process_id_))return false;stopping_.store(false);try{reader_thread_=std::thread(&CloudOSNativeTerminalWindow::ReaderLoop,this);}catch(...){cloudos_native_terminal_terminate(terminal_,1);cloudos_native_terminal_release(terminal_);terminal_=nullptr;SetLastError(ERROR_NOT_ENOUGH_MEMORY);return false;}return true;}
void CloudOSNativeTerminalWindow::StopTerminal() noexcept{stopping_.store(true);if(terminal_){DWORD code=0;BOOL exited=FALSE;if(cloudos_native_terminal_get_exit_code(terminal_,&code,&exited)&&!exited)(void)cloudos_native_terminal_terminate(terminal_,0);}if(reader_thread_.joinable()){(void)CancelSynchronousIo(reader_thread_.native_handle());reader_thread_.join();}if(terminal_){cloudos_native_terminal_release(terminal_);terminal_=nullptr;}}
void CloudOSNativeTerminalWindow::ReaderLoop(){std::array<char,8192>b{};while(!stopping_.load()){DWORD n=0;if(!cloudos_native_terminal_read(terminal_,b.data(),static_cast<DWORD>(b.size()),&n)||n==0)break;ConsumeOutputBytes(b.data(),n);if(window_)PostMessageW(window_,WM_OUTPUT,0,0);}if(!stopping_.load()&&terminal_){DWORD code=0;BOOL exited=FALSE;if(cloudos_native_terminal_get_exit_code(terminal_,&code,&exited)&&exited){wchar_t t[100]{};swprintf_s(t,L"\r\n[processo encerrado: %lu]\r\n",code);AppendText(t);}}if(window_)PostMessageW(window_,WM_OUTPUT,0,0);}
void CloudOSNativeTerminalWindow::ConsumeOutputBytes(const char* bytes,DWORD size){for(DWORD i=0;i<size;++i){unsigned char v=static_cast<unsigned char>(bytes[i]);if(ansi_state_==1){ansi_state_=v=='['?2:0;continue;}if(ansi_state_==2){if(v>=0x40&&v<=0x7e)ansi_state_=0;continue;}if(v==0x1b){ansi_state_=1;continue;}pending_utf8_.push_back(static_cast<char>(v));}FlushUtf8Pending();}
void CloudOSNativeTerminalWindow::FlushUtf8Pending(){while(!pending_utf8_.empty()){size_t valid=pending_utf8_.size();int required=0;for(size_t trim=0;trim<=3&&trim<pending_utf8_.size();++trim){valid=pending_utf8_.size()-trim;required=MultiByteToWideChar(CP_UTF8,MB_ERR_INVALID_CHARS,pending_utf8_.data(),static_cast<int>(valid),nullptr,0);if(required>0)break;}if(required<=0){if(pending_utf8_.size()>4){AppendText(L"?");pending_utf8_.erase(pending_utf8_.begin());continue;}return;}std::wstring w(static_cast<size_t>(required),L'\0');if(MultiByteToWideChar(CP_UTF8,MB_ERR_INVALID_CHARS,pending_utf8_.data(),static_cast<int>(valid),w.data(),required)<=0)return;std::wstring clean;clean.reserve(w.size());for(wchar_t ch:w){if(ch==L'\r')continue;if(ch==L'\b'){if(!clean.empty())clean.pop_back();continue;}if(ch==L'\n'||ch==L'\t'||ch>=L' ')clean.push_back(ch);}AppendText(clean);pending_utf8_.erase(pending_utf8_.begin(),pending_utf8_.begin()+static_cast<ptrdiff_t>(valid));if(valid==0)break;}}
void CloudOSNativeTerminalWindow::AppendText(std::wstring_view s){if(s.empty())return;std::lock_guard lock(output_mutex_);output_.append(s);if(output_.size()>MAX_SCROLL)output_.erase(0,output_.size()-MAX_SCROLL);}
void CloudOSNativeTerminalWindow::WriteBytes(const void* p,DWORD n){if(!terminal_||!p||!n)return;auto*b=static_cast<const std::byte*>(p);DWORD off=0;while(off<n){DWORD w=0;if(!cloudos_native_terminal_write(terminal_,b+off,n-off,&w)||!w)break;off+=w;}}
void CloudOSNativeTerminalWindow::WriteUtf8(std::wstring_view s){auto u=ToUtf8(s);if(!u.empty())WriteBytes(u.data(),static_cast<DWORD>(u.size()));}
void CloudOSNativeTerminalWindow::PasteClipboard(){if(!OpenClipboard(window_))return;HANDLE h=GetClipboardData(CF_UNICODETEXT);if(h){auto*t=static_cast<const wchar_t*>(GlobalLock(h));if(t){WriteUtf8(t);GlobalUnlock(h);}}CloseClipboard();}
void CloudOSNativeTerminalWindow::ResizeTerminal(){if(!terminal_||!window_)return;RECT r{};if(!GetClientRect(window_,&r))return;SHORT c=static_cast<SHORT>(std::clamp((r.right-r.left)/std::max(1,cell_width_),20,240));SHORT rows=static_cast<SHORT>(std::clamp((r.bottom-r.top)/std::max(1,cell_height_),5,120));(void)cloudos_native_terminal_resize(terminal_,c,rows);}
void CloudOSNativeTerminalWindow::UpdateFontMetrics(){if(font_)DeleteObject(font_);UINT dpi=window_?GetDpiForWindow(window_):96;font_=CreateFontW(-MulDiv(15,static_cast<int>(dpi),96),0,0,0,FW_NORMAL,FALSE,FALSE,FALSE,DEFAULT_CHARSET,OUT_DEFAULT_PRECIS,CLIP_DEFAULT_PRECIS,CLEARTYPE_QUALITY,FIXED_PITCH|FF_MODERN,L"Consolas");if(!font_)return;HDC dc=GetDC(window_);if(!dc)return;auto old=SelectObject(dc,font_);TEXTMETRICW tm{};if(GetTextMetricsW(dc,&tm)){cell_width_=std::max(1,tm.tmAveCharWidth);cell_height_=std::max(1,tm.tmHeight+tm.tmExternalLeading);}SelectObject(dc,old);ReleaseDC(window_,dc);}
std::vector<std::wstring> CloudOSNativeTerminalWindow::VisibleLines() const{RECT r{};if(!window_||!GetClientRect(window_,&r))return{};size_t rows=static_cast<size_t>(std::max(1,(r.bottom-r.top)/std::max(1,cell_height_)));std::vector<std::wstring> out;std::lock_guard lock(output_mutex_);size_t end=output_.size();while(end>0&&out.size()<rows){size_t pos=output_.rfind(L'\n',end-1);size_t start=pos==std::wstring::npos?0:pos+1;out.push_back(output_.substr(start,end-start));if(pos==std::wstring::npos)break;end=pos;}std::reverse(out.begin(),out.end());return out;}
void CloudOSNativeTerminalWindow::Paint(){PAINTSTRUCT ps{};HDC dc=BeginPaint(window_,&ps);RECT r{};GetClientRect(window_,&r);HBRUSH bg=CreateSolidBrush(RGB(12,15,20));FillRect(dc,&r,bg);DeleteObject(bg);SetBkMode(dc,TRANSPARENT);SetTextColor(dc,RGB(232,236,242));HGDIOBJ old=nullptr;if(font_)old=SelectObject(dc,font_);int y=4;for(auto&line:VisibleLines()){TextOutW(dc,6,y,line.data(),static_cast<int>(line.size()));y+=cell_height_;if(y>=r.bottom)break;}if(old)SelectObject(dc,old);EndPaint(window_,&ps);}
LRESULT CloudOSNativeTerminalWindow::HandleMessage(UINT m,WPARAM w,LPARAM l){switch(m){case WM_OUTPUT:InvalidateRect(window_,nullptr,FALSE);return 0;case WM_PAINT:Paint();return 0;case WM_ERASEBKGND:return 1;case WM_SIZE:ResizeTerminal();return 0;case WM_DPICHANGED:{auto*r=reinterpret_cast<RECT*>(l);SetWindowPos(window_,nullptr,r->left,r->top,r->right-r->left,r->bottom-r->top,SWP_NOZORDER|SWP_NOACTIVATE);UpdateFontMetrics();ResizeTerminal();return 0;}case WM_KEYDOWN:{bool ctrl=(GetKeyState(VK_CONTROL)&0x8000)!=0;if(ctrl&&(w==L'V'||w==L'v')){PasteClipboard();return 0;}switch(w){case VK_UP:WriteBytes("\x1b[A",3);return 0;case VK_DOWN:WriteBytes("\x1b[B",3);return 0;case VK_RIGHT:WriteBytes("\x1b[C",3);return 0;case VK_LEFT:WriteBytes("\x1b[D",3);return 0;case VK_HOME:WriteBytes("\x1b[H",3);return 0;case VK_END:WriteBytes("\x1b[F",3);return 0;case VK_DELETE:WriteBytes("\x1b[3~",4);return 0;}break;}case WM_CHAR:{wchar_t ch=static_cast<wchar_t>(w);if(ch==L'\b'){char x=0x7f;WriteBytes(&x,1);}else if(ch==L'\r'){char x='\r';WriteBytes(&x,1);}else if(ch==L'\t'){char x='\t';WriteBytes(&x,1);}else if(ch>0){wchar_t s[2]{ch,0};WriteUtf8(s);}return 0;}case WM_CLOSE:StopTerminal();DestroyWindow(window_);return 0;case WM_NCDESTROY:window_=nullptr;delete this;return 0;}return DefWindowProcW(window_,m,w,l);}
LRESULT CALLBACK CloudOSNativeTerminalWindow::WindowProcedure(HWND h,UINT m,WPARAM w,LPARAM l){auto*p=m==WM_NCCREATE?static_cast<CloudOSNativeTerminalWindow*>(reinterpret_cast<CREATESTRUCTW*>(l)->lpCreateParams):reinterpret_cast<CloudOSNativeTerminalWindow*>(GetWindowLongPtrW(h,GWLP_USERDATA));if(m==WM_NCCREATE&&p){p->window_=h;SetWindowLongPtrW(h,GWLP_USERDATA,reinterpret_cast<LONG_PTR>(p));}return p?p->HandleMessage(m,w,l):DefWindowProcW(h,m,w,l);}
