#include "native_files_window.h"
#include <commctrl.h>
#include <shellapi.h>
#include <algorithm>
#include <array>
#include <cwchar>
#include <iterator>
#include <new>
#include <utility>
#pragma comment(lib,"comctl32.lib")
namespace{constexpr wchar_t kClass[]=L"CloudOS.Native.Files.v1";constexpr int ID_PATH=1201,ID_GO=1202,ID_UP=1203,ID_WSL=1204,ID_LIST=1205;bool Register(HINSTANCE h){WNDCLASSEXW w{sizeof(w)};w.lpfnWndProc=&CloudOSNativeFilesWindow::WindowProcedure;w.hInstance=h;w.hCursor=LoadCursorW(nullptr,IDC_ARROW);w.hbrBackground=reinterpret_cast<HBRUSH>(COLOR_WINDOW+1);w.lpszClassName=kClass;return RegisterClassExW(&w)!=0||GetLastError()==ERROR_CLASS_ALREADY_EXISTS;}std::wstring EditText(HWND h){int n=GetWindowTextLengthW(h);std::wstring s(static_cast<size_t>(n)+1,L'\0');if(n>0){GetWindowTextW(h,s.data(),n+1);s.resize(static_cast<size_t>(n));}else s.clear();return s;}std::wstring DefaultPath(){std::array<wchar_t,MAX_PATH> b{};if(GetWindowsDirectoryW(b.data(),static_cast<UINT>(b.size()))>0){std::wstring p=b.data();if(p.size()>=3)return p.substr(0,3);}return L"C:\\";}}
CloudOSNativeFilesWindow::CloudOSNativeFilesWindow(HINSTANCE i,std::wstring p):instance_(i),current_path_(std::move(p)){if(current_path_.empty())current_path_=DefaultPath();}
void CloudOSNativeFilesWindow::Open(HINSTANCE i,const std::wstring&p){auto*x=new(std::nothrow)CloudOSNativeFilesWindow(i,p);if(!x||!x->Create()){delete x;MessageBoxW(nullptr,L"Nao foi possivel abrir Arquivos.",L"CloudOS",MB_OK|MB_ICONERROR);}}
bool CloudOSNativeFilesWindow::Create(){if(!Register(instance_))return false;window_=CreateWindowExW(WS_EX_APPWINDOW,kClass,L"Arquivos - CloudOS",WS_OVERLAPPEDWINDOW,CW_USEDEFAULT,CW_USEDEFAULT,980,650,nullptr,nullptr,instance_,this);if(!window_)return false;path_edit_=CreateWindowExW(WS_EX_CLIENTEDGE,L"EDIT",current_path_.c_str(),WS_CHILD|WS_VISIBLE|ES_AUTOHSCROLL,0,0,0,0,window_,reinterpret_cast<HMENU>(ID_PATH),instance_,nullptr);go_button_=CreateWindowW(L"BUTTON",L"Ir",WS_CHILD|WS_VISIBLE,0,0,0,0,window_,reinterpret_cast<HMENU>(ID_GO),instance_,nullptr);up_button_=CreateWindowW(L"BUTTON",L"Acima",WS_CHILD|WS_VISIBLE,0,0,0,0,window_,reinterpret_cast<HMENU>(ID_UP),instance_,nullptr);wsl_button_=CreateWindowW(L"BUTTON",L"WSL",WS_CHILD|WS_VISIBLE,0,0,0,0,window_,reinterpret_cast<HMENU>(ID_WSL),instance_,nullptr);list_=CreateWindowExW(WS_EX_CLIENTEDGE,WC_LISTVIEWW,L"",WS_CHILD|WS_VISIBLE|LVS_REPORT|LVS_SINGLESEL,0,0,0,0,window_,reinterpret_cast<HMENU>(ID_LIST),instance_,nullptr);ListView_SetExtendedListViewStyle(list_,LVS_EX_FULLROWSELECT|LVS_EX_DOUBLEBUFFER);LVCOLUMNW c{LVCF_TEXT|LVCF_WIDTH};c.cx=520;c.pszText=const_cast<wchar_t*>(L"Nome");ListView_InsertColumn(list_,0,&c);c.cx=130;c.pszText=const_cast<wchar_t*>(L"Tipo");ListView_InsertColumn(list_,1,&c);c.cx=150;c.pszText=const_cast<wchar_t*>(L"Tamanho");ListView_InsertColumn(list_,2,&c);Navigate(current_path_);ShowWindow(window_,SW_SHOW);return true;}
void CloudOSNativeFilesWindow::Layout(){RECT r{};GetClientRect(window_,&r);int w=r.right,h=r.bottom;MoveWindow(up_button_,12,12,76,30,TRUE);MoveWindow(wsl_button_,94,12,64,30,TRUE);MoveWindow(path_edit_,166,12,max(100,w-236),30,TRUE);MoveWindow(go_button_,max(166,w-62),12,50,30,TRUE);MoveWindow(list_,12,52,max(100,w-24),max(80,h-64),TRUE);}
std::wstring CloudOSNativeFilesWindow::JoinPath(const std::wstring&d,const std::wstring&n){if(d.empty())return n;if(d.back()==L'\\'||d.back()==L'/')return d+n;return d+L"\\"+n;}
std::wstring CloudOSNativeFilesWindow::ParentPath(const std::wstring&p){if(IsRootPath(p))return p;std::wstring x=p;while(x.size()>3&&(x.back()==L'\\'||x.back()==L'/'))x.pop_back();size_t pos=x.find_last_of(L"\\/");if(pos==std::wstring::npos)return x;if(pos==2&&x.size()>2&&x[1]==L':')return x.substr(0,3);if(x.rfind(L"\\\\wsl",0)==0){size_t prefix=x.find(L'\\',2);if(prefix!=std::wstring::npos){size_t distro=x.find(L'\\',prefix+1);if(distro==std::wstring::npos)return x;}}return pos==0?L"\\":x.substr(0,pos);}
bool CloudOSNativeFilesWindow::IsRootPath(const std::wstring&p){if(p.size()==3&&p[1]==L':'&&(p[2]==L'\\'||p[2]==L'/'))return true;if(p==L"\\\\wsl$"||p==L"\\\\wsl$\\"||p==L"\\\\wsl.localhost"||p==L"\\\\wsl.localhost\\")return true;return false;}
std::wstring CloudOSNativeFilesWindow::FormatSize(ULONGLONG s){wchar_t b[64]{};if(s>=1024ull*1024ull*1024ull)swprintf_s(b,L"%.2f GB",static_cast<double>(s)/(1024.0*1024.0*1024.0));else if(s>=1024ull*1024ull)swprintf_s(b,L"%.1f MB",static_cast<double>(s)/(1024.0*1024.0));else if(s>=1024ull)swprintf_s(b,L"%.1f KB",static_cast<double>(s)/1024.0);else swprintf_s(b,L"%llu B",s);return b;}
void CloudOSNativeFilesWindow::Navigate(const std::wstring&p){DWORD a=GetFileAttributesW(p.c_str());if(a==INVALID_FILE_ATTRIBUTES||(a&FILE_ATTRIBUTE_DIRECTORY)==0){MessageBoxW(window_,L"Pasta nao encontrada ou sem acesso.",L"CloudOS Arquivos",MB_OK|MB_ICONWARNING);return;}current_path_=p;SetWindowTextW(path_edit_,current_path_.c_str());PopulateList();}
void CloudOSNativeFilesWindow::NavigateParent(){auto p=ParentPath(current_path_);if(!p.empty())Navigate(p);}
void CloudOSNativeFilesWindow::NavigateWslRoot(){if(GetFileAttributesW(L"\\\\wsl.localhost\\")!=INVALID_FILE_ATTRIBUTES)Navigate(L"\\\\wsl.localhost\\");else Navigate(L"\\\\wsl$\\");}
void CloudOSNativeFilesWindow::PopulateList(){entries_.clear();ListView_DeleteAllItems(list_);std::wstring pattern=JoinPath(current_path_,L"*");WIN32_FIND_DATAW fd{};HANDLE f=FindFirstFileW(pattern.c_str(),&fd);if(f==INVALID_HANDLE_VALUE)return;do{if(wcscmp(fd.cFileName,L".")==0||wcscmp(fd.cFileName,L"..")==0)continue;Entry e{};e.name=fd.cFileName;e.full_path=JoinPath(current_path_,e.name);e.directory=(fd.dwFileAttributes&FILE_ATTRIBUTE_DIRECTORY)!=0;e.size=(static_cast<ULONGLONG>(fd.nFileSizeHigh)<<32)|fd.nFileSizeLow;entries_.push_back(std::move(e));}while(FindNextFileW(f,&fd));FindClose(f);std::sort(entries_.begin(),entries_.end(),[](const Entry&a,const Entry&b){if(a.directory!=b.directory)return a.directory>b.directory;return _wcsicmp(a.name.c_str(),b.name.c_str())<0;});for(size_t i=0;i<entries_.size();++i){LVITEMW item{};item.mask=LVIF_TEXT;item.iItem=static_cast<int>(i);item.pszText=entries_[i].name.data();ListView_InsertItem(list_,&item);wchar_t type[16]{};wcscpy_s(type,entries_[i].directory?L"Pasta":L"Arquivo");ListView_SetItemText(list_,static_cast<int>(i),1,type);auto size=entries_[i].directory?std::wstring{}:FormatSize(entries_[i].size);ListView_SetItemText(list_,static_cast<int>(i),2,size.data());}}
std::wstring CloudOSNativeFilesWindow::SelectedPath() const{int i=ListView_GetNextItem(list_,-1,LVNI_SELECTED);return i>=0&&static_cast<size_t>(i)<entries_.size()?entries_[static_cast<size_t>(i)].full_path:std::wstring{};}
void CloudOSNativeFilesWindow::ActivateSelection(){int i=ListView_GetNextItem(list_,-1,LVNI_SELECTED);if(i<0||static_cast<size_t>(i)>=entries_.size())return;auto&e=entries_[static_cast<size_t>(i)];if(e.directory)Navigate(e.full_path);else{auto r=ShellExecuteW(window_,L"open",e.full_path.c_str(),nullptr,nullptr,SW_SHOWNORMAL);if(reinterpret_cast<INT_PTR>(r)<=32)MessageBoxW(window_,L"O Windows nao encontrou um aplicativo para abrir este arquivo.",L"CloudOS",MB_OK|MB_ICONWARNING);}}
LRESULT CloudOSNativeFilesWindow::HandleMessage(UINT m,WPARAM w,LPARAM l){switch(m){case WM_SIZE:Layout();return 0;case WM_COMMAND:switch(LOWORD(w)){case ID_GO:Navigate(EditText(path_edit_));return 0;case ID_UP:NavigateParent();return 0;case ID_WSL:NavigateWslRoot();return 0;}break;case WM_NOTIFY:{auto*h=reinterpret_cast<NMHDR*>(l);if(h&&h->hwndFrom==list_&&h->code==NM_DBLCLK){ActivateSelection();return 0;}}break;case WM_CLOSE:DestroyWindow(window_);return 0;case WM_NCDESTROY:window_=nullptr;delete this;return 0;}return DefWindowProcW(window_,m,w,l);}
LRESULT CALLBACK CloudOSNativeFilesWindow::WindowProcedure(HWND h,UINT m,WPARAM w,LPARAM l){auto*p=m==WM_NCCREATE?static_cast<CloudOSNativeFilesWindow*>(reinterpret_cast<CREATESTRUCTW*>(l)->lpCreateParams):reinterpret_cast<CloudOSNativeFilesWindow*>(GetWindowLongPtrW(h,GWLP_USERDATA));if(m==WM_NCCREATE&&p){p->window_=h;SetWindowLongPtrW(h,GWLP_USERDATA,reinterpret_cast<LONG_PTR>(p));}return p?p->HandleMessage(m,w,l):DefWindowProcW(h,m,w,l);}
