#include "native_run_window.h"
#include <shellapi.h>
#include <new>
#include <string>
#include <vector>
namespace { constexpr wchar_t kClass[]=L"CloudOS.Native.Run.v1"; constexpr int ID_EDIT=1001,ID_RUN=1002,ID_CANCEL=1003;
bool Register(HINSTANCE h){ WNDCLASSEXW w{sizeof(w)}; w.lpfnWndProc=&CloudOSNativeRunWindow::WindowProcedure; w.hInstance=h; w.hCursor=LoadCursorW(nullptr,IDC_ARROW); w.hbrBackground=reinterpret_cast<HBRUSH>(COLOR_WINDOW+1); w.lpszClassName=kClass; return RegisterClassExW(&w)!=0||GetLastError()==ERROR_CLASS_ALREADY_EXISTS; }
std::wstring Text(HWND h){int n=GetWindowTextLengthW(h); std::wstring s(static_cast<size_t>(n)+1,L'\0'); if(n>0){GetWindowTextW(h,s.data(),n+1);s.resize(static_cast<size_t>(n));}else s.clear();return s;}}
CloudOSNativeRunWindow::CloudOSNativeRunWindow(HINSTANCE i):instance_(i){}
void CloudOSNativeRunWindow::Open(HINSTANCE i){auto*p=new(std::nothrow)CloudOSNativeRunWindow(i);if(!p||!p->Create()){delete p;MessageBoxW(nullptr,L"Nao foi possivel abrir Executar.",L"CloudOS",MB_OK|MB_ICONERROR);}}
bool CloudOSNativeRunWindow::Create(){if(!Register(instance_))return false; window_=CreateWindowExW(WS_EX_TOOLWINDOW,kClass,L"Executar - CloudOS",WS_OVERLAPPED|WS_CAPTION|WS_SYSMENU|WS_THICKFRAME,CW_USEDEFAULT,CW_USEDEFAULT,620,170,nullptr,nullptr,instance_,this);if(!window_)return false; edit_=CreateWindowExW(WS_EX_CLIENTEDGE,L"EDIT",L"",WS_CHILD|WS_VISIBLE|ES_AUTOHSCROLL,0,0,0,0,window_,reinterpret_cast<HMENU>(ID_EDIT),instance_,nullptr); launch_button_=CreateWindowW(L"BUTTON",L"Executar",WS_CHILD|WS_VISIBLE|BS_DEFPUSHBUTTON,0,0,0,0,window_,reinterpret_cast<HMENU>(ID_RUN),instance_,nullptr); cancel_button_=CreateWindowW(L"BUTTON",L"Cancelar",WS_CHILD|WS_VISIBLE,0,0,0,0,window_,reinterpret_cast<HMENU>(ID_CANCEL),instance_,nullptr); SendMessageW(edit_,WM_SETFONT,reinterpret_cast<WPARAM>(GetStockObject(DEFAULT_GUI_FONT)),TRUE);SendMessageW(launch_button_,WM_SETFONT,reinterpret_cast<WPARAM>(GetStockObject(DEFAULT_GUI_FONT)),TRUE);SendMessageW(cancel_button_,WM_SETFONT,reinterpret_cast<WPARAM>(GetStockObject(DEFAULT_GUI_FONT)),TRUE);ShowWindow(window_,SW_SHOW);SetFocus(edit_);return true;}
void CloudOSNativeRunWindow::Layout(){RECT r{};GetClientRect(window_,&r);int w=r.right-r.left;MoveWindow(edit_,16,20,max(100,w-32),30,TRUE);MoveWindow(launch_button_,max(16,w-216),65,96,30,TRUE);MoveWindow(cancel_button_,max(116,w-112),65,96,30,TRUE);}
void CloudOSNativeRunWindow::Launch(){auto command=Text(edit_);if(command.empty())return; std::vector<wchar_t> buffer(command.begin(),command.end());buffer.push_back(L'\0');STARTUPINFOW si{sizeof(si)};PROCESS_INFORMATION pi{};if(CreateProcessW(nullptr,buffer.data(),nullptr,nullptr,FALSE,0,nullptr,nullptr,&si,&pi)){CloseHandle(pi.hThread);CloseHandle(pi.hProcess);DestroyWindow(window_);return;} HINSTANCE h=ShellExecuteW(window_,L"open",command.c_str(),nullptr,nullptr,SW_SHOWNORMAL);if(reinterpret_cast<INT_PTR>(h)>32){DestroyWindow(window_);return;} wchar_t msg[180]{};swprintf_s(msg,L"Nao foi possivel executar. Win32=%lu",GetLastError());MessageBoxW(window_,msg,L"CloudOS",MB_OK|MB_ICONERROR);}
LRESULT CloudOSNativeRunWindow::HandleMessage(UINT m,WPARAM w,LPARAM l){switch(m){case WM_SIZE:Layout();return 0;case WM_COMMAND:switch(LOWORD(w)){case ID_RUN:Launch();return 0;case ID_CANCEL:DestroyWindow(window_);return 0;}break;case WM_CLOSE:DestroyWindow(window_);return 0;case WM_NCDESTROY:window_=nullptr;delete this;return 0;}return DefWindowProcW(window_,m,w,l);}
LRESULT CALLBACK CloudOSNativeRunWindow::WindowProcedure(HWND h,UINT m,WPARAM w,LPARAM l){CloudOSNativeRunWindow*p=m==WM_NCCREATE?static_cast<CloudOSNativeRunWindow*>(reinterpret_cast<CREATESTRUCTW*>(l)->lpCreateParams):reinterpret_cast<CloudOSNativeRunWindow*>(GetWindowLongPtrW(h,GWLP_USERDATA));if(m==WM_NCCREATE&&p){p->window_=h;SetWindowLongPtrW(h,GWLP_USERDATA,reinterpret_cast<LONG_PTR>(p));}return p?p->HandleMessage(m,w,l):DefWindowProcW(h,m,w,l);}
