param([string]$Staging,[string]$ManifestPath,[string]$ComponentsPath,[string]$SupplyChainPath,[string]$ArtifactAuditPath,[string]$BuildResultPath,[string]$ReportPath)
. (Join-Path $PSScriptRoot 'common.ps1')
. (Join-Path $PSScriptRoot 'artifact-security-lib.ps1')
$paths=Get-CloudOSArtifactPaths;$config=Get-CloudOSProductConfig;$head=Get-CloudOSGitSha
if([string]::IsNullOrWhiteSpace($Staging)){$Staging=$paths.Staging};if([string]::IsNullOrWhiteSpace($ManifestPath)){$ManifestPath=Join-Path $paths.Artifacts 'manifest.json'};if([string]::IsNullOrWhiteSpace($ComponentsPath)){$ComponentsPath=Join-Path $paths.Artifacts 'components.json'};if([string]::IsNullOrWhiteSpace($SupplyChainPath)){$SupplyChainPath=Join-Path $paths.Artifacts 'supply-chain.json'};if([string]::IsNullOrWhiteSpace($ArtifactAuditPath)){$ArtifactAuditPath=Join-Path $paths.Artifacts 'audit\artifact-audit.json'};if([string]::IsNullOrWhiteSpace($BuildResultPath)){$BuildResultPath=Join-Path $paths.Build 'build-result.json'};if([string]::IsNullOrWhiteSpace($ReportPath)){$ReportPath=Join-Path $paths.Artifacts 'audit\artifact-security-report.json'}
$result=Test-CloudOSArtifactSecurity -Staging $Staging -ManifestPath $ManifestPath -ComponentsPath $ComponentsPath -SupplyChainPath $SupplyChainPath -ArtifactAuditPath $ArtifactAuditPath -BuildResultPath $BuildResultPath
$report=[ordered]@{schemaVersion=1;product=$config.product;version=$config.version;head=$head;channel=$config.channel;generatedAt=[DateTimeOffset]::UtcNow.ToString('O');status=$(if($result.ok){'passed'}else{'failed'});checks=[ordered]@{extraExecutables=($result.uninventoried -eq 0);unexpectedDlls=($result.uninventoried -eq 0);hiddenFiles=($result.hiddenFiles -eq 0);duplicatePaths=($result.duplicatePaths -eq 0);anomalousSizes=($result.anomalousSizes -eq 0);originsPresent=($result.missingOrigins -eq 0);licensesPresent=($result.missingLicenses -eq 0);hashesMatch=($result.hashMismatches -eq 0);componentsInventoried=($result.uninventoried -eq 0)};counts=[ordered]@{manifestFiles=$result.manifestFiles;actualFiles=$result.actualFiles;binaries=$result.binaries;errors=@($result.errors).Count};errors=@($result.errors)}
Write-CloudOSJson $report $ReportPath 30
if(-not $result.ok){throw "PRODUCTIZATION_SUPPLY_CHAIN_HARDENING_FAILED:$(@($result.errors)-join ',')"}
Write-Host "PRODUCTIZATION_SUPPLY_CHAIN_HARDENING_OK report=$ReportPath binaries=$($result.binaries) hidden=false duplicates=false sizes=true origins=true licenses=true hashes=true inventory=true"
