param([string]$ArtifactsRoot,[string]$LocalRoot,[string]$OutputPath)
. (Join-Path $PSScriptRoot 'common.ps1')
$config=Get-CloudOSProductConfig;$sha=Get-CloudOSGitSha;$paths=Get-CloudOSArtifactPaths
if([string]::IsNullOrWhiteSpace($ArtifactsRoot)){$ArtifactsRoot=$paths.Artifacts}
if([string]::IsNullOrWhiteSpace($LocalRoot)){if($env:CLOUDOS_LOCAL_ROOT){$LocalRoot=$env:CLOUDOS_LOCAL_ROOT}elseif($IsWindows){$LocalRoot=Join-Path $env:LOCALAPPDATA 'CloudOS'}else{$LocalRoot=Join-Path ([IO.Path]::GetTempPath()) 'CloudOS'}}
if([string]::IsNullOrWhiteSpace($OutputPath)){$OutputPath=Join-Path $ArtifactsRoot 'diagnostics\CloudOSDiagnostics.zip'}
$required=[ordered]@{'manifest.json'=(Join-Path $ArtifactsRoot 'manifest.json');'components.json'=(Join-Path $ArtifactsRoot 'components.json');'checksums.sha256'=(Join-Path $ArtifactsRoot 'checksums.sha256');'supply-chain.json'=(Join-Path $ArtifactsRoot 'supply-chain.json');'artifact-audit.json'=(Join-Path $ArtifactsRoot 'audit\artifact-audit.json')}
foreach($entry in $required.GetEnumerator()){if(-not(Test-Path -LiteralPath $entry.Value -PathType Leaf)){throw "DIAGNOSTICS_REQUIRED_ARTIFACT_MISSING:$($entry.Key)"}}
$work=Join-Path ([IO.Path]::GetTempPath()) "CloudOSDiagnostics-$([Guid]::NewGuid().ToString('N'))";$payload=Join-Path $work 'payload';New-Item -ItemType Directory -Force -Path $payload|Out-Null
function Write-JsonFile([object]$Value,[string]$Name){$Value|ConvertTo-Json -Depth 30|Set-Content -LiteralPath (Join-Path $payload $Name) -Encoding utf8}
function Sanitize-Line([string]$Line){$value=$Line;$value=[regex]::Replace($value,'(?i)(authorization\s*:\s*bearer\s+)\S+','$1[REDACTED]');$value=[regex]::Replace($value,'(?i)\b(password|passwd|token|secret|api[_-]?key|recovery[_-]?code|grant)\b\s*[:=]\s*([^\s,;]+)','$1=[REDACTED]');$value=[regex]::Replace($value,'\beyJ[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}\b','[REDACTED_JWT]');if($value.Length -gt 8192){$value=$value.Substring(0,8192)};return $value}
try{
  foreach($entry in $required.GetEnumerator()){Copy-Item -LiteralPath $entry.Value -Destination (Join-Path $payload $entry.Key) -Force}
  $security=Join-Path $ArtifactsRoot 'audit\artifact-security-report.json';if(Test-Path -LiteralPath $security -PathType Leaf){Copy-Item -LiteralPath $security -Destination (Join-Path $payload 'artifact-security-report.json') -Force}
  Write-JsonFile ([ordered]@{schemaVersion=1;product=$config.product;version=$config.version;head=$sha;channel=$config.channel;rid=$config.rid;signing=$config.signing}) 'version.json'
  $runtime=[ordered]@{schemaVersion=1;os=[Environment]::OSVersion.VersionString;architecture=[Runtime.InteropServices.RuntimeInformation]::OSArchitecture.ToString();processArchitecture=[Runtime.InteropServices.RuntimeInformation]::ProcessArchitecture.ToString();powershell=$PSVersionTable.PSVersion.ToString();packagedNode=$null;core=$null}
  $staging=Join-Path $ArtifactsRoot "staging\$($config.version)\$($config.rid)";$node=Join-Path $staging 'runtime\node.exe';if(Test-Path -LiteralPath $node -PathType Leaf){try{$runtime.packagedNode=((& $node --version 2>&1|Out-String).Trim())}catch{$runtime.packagedNode='probe-failed'}};$core=Join-Path $staging 'runtime\cloudos-core';if(Test-Path -LiteralPath $core -PathType Leaf){$runtime.core=[ordered]@{present=$true;sha256=(Get-FileHash -LiteralPath $core -Algorithm SHA256).Hash.ToLowerInvariant()}};Write-JsonFile $runtime 'runtime-inventory.json'
  $probes=[ordered]@{schemaVersion=1;manifest=[ordered]@{present=$true;jsonValid=$true};components=[ordered]@{present=$true;jsonValid=$true};checksums=[ordered]@{present=$true};supplyChain=[ordered]@{present=$true;jsonValid=$true};artifactAudit=[ordered]@{present=$true;jsonValid=$true};artifactSecurity=[ordered]@{present=(Test-Path -LiteralPath $security -PathType Leaf)}}
  foreach($jsonName in @('manifest.json','components.json','supply-chain.json','artifact-audit.json')){try{Get-Content -LiteralPath (Join-Path $payload $jsonName) -Raw|ConvertFrom-Json|Out-Null}catch{throw "DIAGNOSTICS_JSON_INVALID:$jsonName"}};if($probes.artifactSecurity.present){try{Get-Content -LiteralPath (Join-Path $payload 'artifact-security-report.json') -Raw|ConvertFrom-Json|Out-Null}catch{throw 'DIAGNOSTICS_JSON_INVALID:artifact-security-report.json'}};Write-JsonFile $probes 'probes.json'
  $logsOut=Join-Path $payload 'logs';New-Item -ItemType Directory -Force -Path $logsOut|Out-Null;$logsIn=Join-Path $LocalRoot 'logs';$logInventory=New-Object System.Collections.Generic.List[object]
  if(Test-Path -LiteralPath $logsIn -PathType Container){$index=0;foreach($log in Get-ChildItem -LiteralPath $logsIn -File -ErrorAction SilentlyContinue|Sort-Object LastWriteTimeUtc -Descending|Select-Object -First 20){$index++;$safeName=("{0:D2}-{1}" -f $index,([IO.Path]::GetFileName($log.Name)));$destination=Join-Path $logsOut $safeName;$lines=Get-Content -LiteralPath $log.FullName -ErrorAction SilentlyContinue|Select-Object -Last 4000|ForEach-Object{Sanitize-Line ([string]$_)};Set-Content -LiteralPath $destination -Value $lines -Encoding utf8;$logInventory.Add([pscustomobject]@{file="logs/$safeName";sourceName=$log.Name;sourceBytes=$log.Length})}}
  Write-JsonFile ($logInventory.ToArray()) 'logs-inventory.json'
  $forbiddenNames=@('cloudos.json','database.json','grants.json','grant.json','.env');$payloadFiles=Get-ChildItem -LiteralPath $payload -File -Recurse;foreach($file in $payloadFiles){if($forbiddenNames -contains $file.Name.ToLowerInvariant()){throw "DIAGNOSTICS_FORBIDDEN_FILE:$($file.Name)"}}
  $scan=($payloadFiles|Where-Object{$_.Extension -in @('.json','.txt','.log','.sha256')}|ForEach-Object{Get-Content -LiteralPath $_.FullName -Raw -ErrorAction SilentlyContinue}) -join "`n";if($scan -match '(?i)\b(password|passwd|token|secret|api[_-]?key|recovery[_-]?code|grant)\b\s*[:=]\s*(?!\[REDACTED\])\S+'){throw 'DIAGNOSTICS_SECRET_PATTERN_REMAINED'};if($scan -match '\beyJ[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}\b'){throw 'DIAGNOSTICS_JWT_REMAINED'}
  $parent=Split-Path -Parent $OutputPath;if($parent){New-Item -ItemType Directory -Force -Path $parent|Out-Null};Remove-Item -LiteralPath $OutputPath -Force -ErrorAction SilentlyContinue;Compress-Archive -Path (Join-Path $payload '*') -DestinationPath $OutputPath -CompressionLevel Optimal;if(-not(Test-Path -LiteralPath $OutputPath -PathType Leaf)){throw 'DIAGNOSTICS_ZIP_NOT_CREATED'}
  Write-Host "PRODUCTIZATION_DIAGNOSTICS_OK path=$OutputPath logs=$($logInventory.Count) secrets=false userData=false grants=false";return $OutputPath
}finally{Remove-Item -LiteralPath $work -Recurse -Force -ErrorAction SilentlyContinue}
