. (Join-Path $PSScriptRoot 'common.ps1')
. (Join-Path $PSScriptRoot 'artifact-security-lib.ps1')
$root=Join-Path ([IO.Path]::GetTempPath()) "artifact-security-test-$([Guid]::NewGuid().ToString('N'))";$stage=Join-Path $root 'stage';$build=Join-Path $root 'build';$auditDir=Join-Path $root 'audit';New-Item -ItemType Directory -Force -Path $stage,$build,$auditDir,(Join-Path $stage 'runtime'),(Join-Path $stage 'meta\licenses'),(Join-Path $stage 'meta\SBOM')|Out-Null
$bootstrap=Join-Path $build 'bootstrap';New-Item -ItemType Directory -Force -Path $bootstrap|Out-Null;Set-Content -LiteralPath (Join-Path $bootstrap 'CloudOS.Bootstrap.exe') -Value 'bootstrap' -Encoding utf8;Copy-Item -LiteralPath (Join-Path $bootstrap 'CloudOS.Bootstrap.exe') -Destination (Join-Path $stage 'CloudOS.Bootstrap.exe');Set-Content -LiteralPath (Join-Path $stage 'runtime\node.exe') -Value 'node' -Encoding utf8;Set-Content -LiteralPath (Join-Path $stage 'runtime\NODE-LICENSE.txt') -Value 'Node license' -Encoding utf8;Set-Content -LiteralPath (Join-Path $stage 'meta\licenses\THIRD-PARTY-NOTICES.txt') -Value 'notices' -Encoding utf8;'{"components":[]}'|Set-Content -LiteralPath (Join-Path $stage 'meta\SBOM\npm.cyclonedx.json') -Encoding utf8;'{}'|Set-Content -LiteralPath (Join-Path $stage 'meta\SBOM\nuget-host.json') -Encoding utf8;'{}'|Set-Content -LiteralPath (Join-Path $stage 'meta\SBOM\nuget-bootstrap.json') -Encoding utf8;'{}'|Set-Content -LiteralPath (Join-Path $stage 'meta\SBOM\go-modules.jsonl') -Encoding utf8;Set-Content -LiteralPath (Join-Path $stage 'runtime\cloudos-core') -Value 'core' -Encoding utf8
$nodeHash=(Get-FileHash -LiteralPath (Join-Path $stage 'runtime\node.exe') -Algorithm SHA256).Hash.ToLowerInvariant();$coreHash=(Get-FileHash -LiteralPath (Join-Path $stage 'runtime\cloudos-core') -Algorithm SHA256).Hash.ToLowerInvariant();$buildResultPath=Join-Path $build 'build-result.json';[ordered]@{host=(Join-Path $build 'host');backend=(Join-Path $build 'backend');frontend=(Join-Path $build 'frontend');bootstrap=$bootstrap;core=(Join-Path $stage 'runtime\cloudos-core');coreSha256=$coreHash}|ConvertTo-Json|Set-Content -LiteralPath $buildResultPath -Encoding utf8
$componentsPath=Join-Path $root 'components.json';[ordered]@{schemaVersion=2;components=@([ordered]@{name='Bootstrap';path='CloudOS.Bootstrap.exe';origin='repository:bootstrap';evidence='build'},[ordered]@{name='node';path='runtime/node.exe';origin='https://node.example/node.zip';evidence='hash';sha256=$nodeHash},[ordered]@{name='core';path='runtime/cloudos-core';origin='repository:core';evidence='build';sha256=$coreHash})}|ConvertTo-Json -Depth 8|Set-Content -LiteralPath $componentsPath -Encoding utf8
$supplyPath=Join-Path $root 'supply.json';[ordered]@{schemaVersion=1;components=@([ordered]@{name='Bootstrap';origin='repository:bootstrap';evidence='build';licenseEvidence='repository notices'},[ordered]@{name='Node';origin='https://node.example/node.zip';evidence='hash';licenseEvidence='runtime/NODE-LICENSE.txt'},[ordered]@{name='core';origin='repository:core';evidence='build';licenseEvidence='module inventory'})}|ConvertTo-Json -Depth 8|Set-Content -LiteralPath $supplyPath -Encoding utf8;$auditPath=Join-Path $auditDir 'artifact-audit.json';'{"status":"passed"}'|Set-Content -LiteralPath $auditPath -Encoding utf8
function Write-Manifest{$items=@(Get-ChildItem -LiteralPath $stage -File -Recurse -Force|Sort-Object FullName|ForEach-Object{[ordered]@{path=[IO.Path]::GetRelativePath($stage,$_.FullName).Replace('\','/');size=$_.Length;sha256=(Get-FileHash -LiteralPath $_.FullName -Algorithm SHA256).Hash.ToLowerInvariant()}});[ordered]@{schemaVersion=1;files=$items}|ConvertTo-Json -Depth 8|Set-Content -LiteralPath (Join-Path $root 'manifest.json') -Encoding utf8}
function Run-Test{Write-Manifest;return Test-CloudOSArtifactSecurity -Staging $stage -ManifestPath (Join-Path $root 'manifest.json') -ComponentsPath $componentsPath -SupplyChainPath $supplyPath -ArtifactAuditPath $auditPath -BuildResultPath $buildResultPath}
try{
 $base=Run-Test;if(-not $base.ok){throw "ARTIFACT_SECURITY_BASE_FIXTURE_FAILED:$(@($base.errors)-join ',')"}
 $extra=Join-Path $stage 'rogue.exe';Set-Content -LiteralPath $extra -Value 'rogue' -Encoding utf8;$r=Run-Test;if($r.ok -or -not(@($r.errors|Where-Object{$_ -like 'origin-missing:*'}).Count -gt 0)){throw 'ARTIFACT_SECURITY_NEGATIVE_NOT_REJECTED:extra'};Remove-Item $extra -Force
 Write-Manifest;$m=Get-Content -LiteralPath (Join-Path $root 'manifest.json') -Raw|ConvertFrom-Json;$m.files[0].sha256=('0'*64);$m|ConvertTo-Json -Depth 8|Set-Content -LiteralPath (Join-Path $root 'manifest.json') -Encoding utf8;$r=Test-CloudOSArtifactSecurity -Staging $stage -ManifestPath (Join-Path $root 'manifest.json') -ComponentsPath $componentsPath -SupplyChainPath $supplyPath -ArtifactAuditPath $auditPath -BuildResultPath $buildResultPath;if($r.ok -or -not(@($r.errors|Where-Object{$_ -like 'hash:*'}).Count -gt 0)){throw 'ARTIFACT_SECURITY_NEGATIVE_NOT_REJECTED:hash'}
 $hidden=Join-Path $stage '.hidden.dll';Set-Content $hidden 'hidden';$r=Run-Test;if($r.ok -or -not(@($r.errors|Where-Object{$_ -like 'hidden-path:*'}).Count -gt 0)){throw 'ARTIFACT_SECURITY_NEGATIVE_NOT_REJECTED:hidden'};Remove-Item $hidden -Force
 $s=Get-Content $supplyPath -Raw|ConvertFrom-Json;$s.components[0].licenseEvidence='';$s|ConvertTo-Json -Depth 8|Set-Content $supplyPath -Encoding utf8;$r=Run-Test;if($r.ok -or -not(@($r.errors|Where-Object{$_ -like 'license-missing:*'}).Count -gt 0)){throw 'ARTIFACT_SECURITY_NEGATIVE_NOT_REJECTED:license'};$s.components[0].licenseEvidence='repository notices';$s|ConvertTo-Json -Depth 8|Set-Content $supplyPath -Encoding utf8
 $c=Get-Content $componentsPath -Raw|ConvertFrom-Json;$c.components[0].origin='';$c|ConvertTo-Json -Depth 8|Set-Content $componentsPath -Encoding utf8;$r=Run-Test;if($r.ok -or -not(@($r.errors|Where-Object{$_ -like 'component-origin-missing:*'}).Count -gt 0)){throw 'ARTIFACT_SECURITY_NEGATIVE_NOT_REJECTED:origin'}
 Write-Host 'PRODUCTIZATION_SUPPLY_CHAIN_NEGATIVE_TESTS_OK extraExe=true hash=true hidden=true license=true origin=true'
}finally{Remove-Item -LiteralPath $root -Recurse -Force -ErrorAction SilentlyContinue}
