. (Join-Path $PSScriptRoot 'common.ps1')
$root=Join-Path ([IO.Path]::GetTempPath()) "cloudos-diagnostics-test-$([Guid]::NewGuid().ToString('N'))";$artifacts=Join-Path $root 'artifacts';$local=Join-Path $root 'local';$out=Join-Path $root 'out\CloudOSDiagnostics.zip'
New-Item -ItemType Directory -Force -Path (Join-Path $artifacts 'audit'),(Join-Path $local 'logs'),(Join-Path $local 'data'),(Join-Path $local 'grants')|Out-Null
function J([string]$Path,[object]$Value){$Value|ConvertTo-Json -Depth 20|Set-Content -LiteralPath $Path -Encoding utf8}
try{
  J (Join-Path $artifacts 'manifest.json') ([ordered]@{schemaVersion=1;product='CloudOS';version='1.1.0-batch2.1';head=(Get-CloudOSGitSha);channel='development';files=@()});J (Join-Path $artifacts 'components.json') ([ordered]@{schemaVersion=2;components=@()});Set-Content -LiteralPath (Join-Path $artifacts 'checksums.sha256') -Value 'fixture  fixture' -Encoding utf8;J (Join-Path $artifacts 'supply-chain.json') ([ordered]@{schemaVersion=1;components=@()});J (Join-Path $artifacts 'audit\artifact-audit.json') ([ordered]@{schemaVersion=1;status='passed'});J (Join-Path $artifacts 'audit\artifact-security-report.json') ([ordered]@{schemaVersion=1;status='passed'})
  @('ordinary log line','password=super-secret-value','token: abcdef123456','Authorization: Bearer eyJabcdefgh.abcdefgh.abcdefgh','grant=my-private-folder')|Set-Content -LiteralPath (Join-Path $local 'logs\app.log') -Encoding utf8;Set-Content -LiteralPath (Join-Path $local 'data\cloudos.json') -Value '{"private":"user"}' -Encoding utf8;Set-Content -LiteralPath (Join-Path $local 'grants\grant.json') -Value '{"path":"C:\\private"}' -Encoding utf8
  & (Join-Path $PSScriptRoot 'export-diagnostics.ps1') -ArtifactsRoot $artifacts -LocalRoot $local -OutputPath $out|Out-Null;if(-not(Test-Path -LiteralPath $out)){throw 'DIAGNOSTICS_TEST_ZIP_MISSING'}
  $extract=Join-Path $root 'extract';Expand-Archive -LiteralPath $out -DestinationPath $extract
  foreach($required in @('manifest.json','components.json','checksums.sha256','version.json','runtime-inventory.json','probes.json','supply-chain.json','artifact-audit.json','artifact-security-report.json','logs-inventory.json')){if(-not(Test-Path -LiteralPath (Join-Path $extract $required))){throw "DIAGNOSTICS_TEST_REQUIRED_MISSING:$required"}}
  if(Get-ChildItem -LiteralPath $extract -File -Recurse|Where-Object{$_.Name -in @('cloudos.json','grant.json','grants.json')}){throw 'DIAGNOSTICS_TEST_PRIVATE_FILE_INCLUDED'}
  $all=(Get-ChildItem -LiteralPath $extract -File -Recurse|ForEach-Object{Get-Content -LiteralPath $_.FullName -Raw -ErrorAction SilentlyContinue}) -join "`n";foreach($secret in @('super-secret-value','abcdef123456','eyJabcdefgh.abcdefgh.abcdefgh','my-private-folder','C:\private')){if($all.Contains($secret,[StringComparison]::OrdinalIgnoreCase)){throw "DIAGNOSTICS_TEST_SECRET_LEAK:$secret"}};if($all -notmatch '\[REDACTED\]'){throw 'DIAGNOSTICS_TEST_REDACTION_MISSING'}
  Write-Host 'PRODUCTIZATION_DIAGNOSTICS_TEST_OK allowlist=true redaction=true privateDataExcluded=true grantsExcluded=true'
}finally{Remove-Item -LiteralPath $root -Recurse -Force -ErrorAction SilentlyContinue}
